### ISSUE TITLE
Regression: GUI: Confusing "done (wd: /)" message during copying files

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [slacka/WoeUSB#103]
This is a regression after the main code refactoring(issue #88), however I don't know how to fix it.

![installing _126](https://user-images.githubusercontent.com/13408130/27026054-1ef4ba88-4f8f-11e7-8523-efa825c75495.png)

**Comment by tvld** [comment]
I clicked "Cancel" and then woeusb responded "are you sure?" ... when I clicked "No", it the bar moved again... Only to stop at 2/3 now... So did it few times more and it seems to be alive ...

**Comment by thedailyhustle** [comment]
Same thing happened here

**Comment by Lin-Buo-Ren** [comment]
This issue should be fixed since WoeUSB v3.0.3 and by commit 0a087ceb67de8e746b0bf2d1977dcfdca79333a1
