### ISSUE TITLE
Binary files in 2.1.0 version no exist in DEB Package and Source Build

### ISSUE THREAD

**Issue by inthemix84** [slacka/WoeUSB#110]
Hello

Today my system upgrade the version of Winusb to 2.1.0 from PPA, but the DEB pack not have a binary executable files, only the "doc" folder.
Then, i download the code form github and build the source, but also when generate the Deb package, i have a problem, also the binary files not exist.

This is a bug ? or is a error on my distribution linux ?

I'm using Ubuntu 16.04 x64

Thank

**Comment by Lin-Buo-Ren** [comment]
Hello, are you using WebUpd8 PPA?  It should be automatically installing `woeusb` package during upgrading `winusb` package.

Refer [Tool To Create Bootable Windows USB Stick From Linux `WinUSB` (Fork) Renamed To `WoeUSB`, Sees New Release ~ Web Upd8: Ubuntu / Linux blog](http://www.webupd8.org/2017/06/tool-to-create-bootable-windows-usb.html) for more details.

P.S. We don't have official PPA for now, so what you said in for certain a third-party PPA

**Comment by inthemix84** [comment]
Hello

Thank you very much for your prompt response. Obviously the owner of the PPA has changed something in their packets, formerly installed as "winusb", now effectively change to "woeusb". Or some other change occurred in my system when updating yesterday.

I've recompiled the github code and I can actually run it with "oeusb".

I always did it with the command "winusb", that is for not using official sources of the program, problem that sometimes generates the use of unofficial PPA.

I apologize and again thank you for your help.

Congratulations on your work and this great tool very useful.

regards
