### ISSUE TITLE
Error in record iso

### ISSUE THREAD

**Issue by Faust30000** [slacka/WoeUSB#112]
Installation failed !
Exit code: 256
Log:
WARNING: The deprecated --format option is still available but will be dropped in WoeUSB v3.0!
Error: Target device is currently busy, unmount all mounted partitions in target device then try again
Target device is busy, please make sure you unmount all filesystems on target device before detaching it.

OS: Linux Mint 18.1 Cinnamon.

**Comment by Lin-Buo-Ren** [comment]
Thanks for reporting, however the error message is pretty clear that one of your target device's partition is currently mounted, so for data protection WoeUSB will bail out.  Please ensure all of the filesystems residing on the target device is unmounted before running WoeUSB.

Please comment if you still has issues related with this matter.

**Comment by MindFreeze** [comment]
Just FYI for anyone who stumbles here. 
I was getting this error, but when I unmount the drive, it didn't show up in WoeUSB anymore. The fix was to format the USB drive. I used NTFS, but don't know if that matters. After that everything worked great.

**Comment by krhil** [comment]
I used FAT but does not work, then I used NTFS and worked great, so the format matters.

**Comment by JuanFontes** [comment]
I had the same problem, when I formated to NTFS, woeusb works. thx @krhil

**Comment by flip111** [comment]
I also had this problem which was fixed after formatting with NTFS. Perhaps this could be in the error message as a suggestion what to do?

**Comment by Lin-Buo-Ren** [comment]
FAQ in the wiki is more suitable for such workarounds

**Comment by Lin-Buo-Ren** [comment]
For anyone that are affected by this issue, please check out https://github.com/slacka/WoeUSB/wiki/F.A.Q.#why-does-woeusb-cant-find-my-external-usb-drive-after-i-use-the-eject-button-in-filemanager-etc-to-unmount-its-filesystems if the method mentioned there can solve your problem.

**Comment by georgegach** [comment]
Disabling GNOME Removable Drive Menu extension and closing File Explorer fixed it for me.

**Comment by zchrissirhcz** [comment]
Same problem here. Actually, I'm on Ubuntu16.04 desktop distribution, and the flash disk will be mounted automatically. Just in your terminal, run the unmount command to unmount your flask disk.

For example, there are 1 SSD and 1 HDD on my machine, and the flask disk is third disk. Thus it is sdc1, and I run this:
```
sudo mount /dev/sdc1
```

Then in WoeUSB GUI, click that button to make your loader.

**Comment by Lin-Buo-Ren** [comment]
Please verify if the following solution works for you:

1. Note all the mounted partitions in the target device via running `lsblk <target device's root block device path, e.g. /dev/sdc>`
2. For each mounted partitions, run the following command: `udisksctl unmount --block-device <mounted partition's block device path, e.g. /dev/sdc1>`
3. Run WoeUSB again and try to reproduce the problem

Removable storage management is a mess on GNOME, this ensures that WoeUSB won't be interfered by the "user-friendly" automounting feature.

**Comment by elasanchez** [comment]
I encountered the same problem where it gave me an error complaining that the partition must unmounted from the filesystem. I unmounted my USB but I couldn't find it in the WoeUSB GUI so I came across this thread and thought  try formatting my USB into NTFS. I searched how to format a disk into NTFS and came across this:

"Whenever we attach a USB drive in [Linux], it automatically mounted to the system. **We can not format any disk on Linux systems which are already mounted.** So first un-mount this USB drive using the following command." - [source article](https://tecadmin.net/format-usb-in-linux/) 

$ sudo umount /dev/sdx

Where /dev/sdx is your USB device. Then I realized that must be the reason why WoeUSB cannot format the device. We should be able to access /dev/sdx even if we cant see it, so I tried the CLI command:

$ sudo woeusb --device Win10_XXX_English_x64.iso /dev/sdx

And it didn't complain and created a win10 bootable usb.

**Comment by KIC** [comment]
@StructByLightning happens if you try the woe gui first and the just exit. The "source" stays mounted.

**Comment by bufface** [comment]
This works for me:
- If you don't see the **_USB_** disk in **_WoeUSB_**, close it.
- Unmount your **_USB_**
- Open **_WoeUSB_** again

_All these steps already assume that you have your USB stick formatted (NTFS)_

**Comment by wheldrak3** [comment]
Just unmounting the usb drive worked for me.

**Comment by NafaaBout** [comment]
None of the above-mentioned solutions worked for me. I used the command line tool with this command
`sudo woeusb --device Win10_Image.iso /dev/sda --tgt-fs NTFS`. 
Working great.

**Comment by jasonxfield** [comment]
> None of the above-mentioned solutions worked for me. I used the command line tool with this command
> `sudo woeusb --device Win10_Image.iso /dev/sda --tgt-fs NTFS`.
> Working great.

Thanks @NafaaBout this is also the only solution that worked for me also.  Saved me much pain, thnx for posting this.

**Comment by miteshtagadiya** [comment]
I have the same issue, woeusb always shows error code 256, I solved by this:
Go to Disks,
![disks](https://user-images.githubusercontent.com/22439269/55854947-bf4f4f00-5b83-11e9-9c50-f3c31f660b16.png)
And Unmount your USB,
And then create USB using woeusb, It's working now.

**Comment by waqashamid** [comment]
> Just FYI for anyone who stumbles here.
> I was getting this error, but when I unmount the drive, it didn't show up in WoeUSB anymore. The fix was to format the USB drive. I used NTFS, but don't know if that matters. After that everything worked great.

I formatted my device to NTFS and it worked!

**Comment by quyle1703** [comment]
Man, all you need is use Gparted to format your usb (the partition you want to mount ISO file on). After that, just do the process again with Woeusb, you're gonna see the magic happens

**Comment by intergalacticvoid** [comment]
> Man, all you need is use Gparted to format your usb (the partition you want to mount ISO file on). After that, just do the process again with Woeusb, you're gonna see the magic happens

All you need is love, because it looks like a buggy BIOS could also play a role in causing malfunction of finding the medium

**Comment by rafid059** [comment]
1. close all gnome apps (disks, files, gparted)

2. remove your usb and then insert it again

3. (https://github.com/slacka/WoeUSB/issues/112#issuecomment-420906018)
>Note all the mounted partitions in the target device via running `lsblk <target device's root block device path, e.g. /dev/sdc>`

>For each mounted partitions, run the following command: `udisksctl unmount --block-device <mounted partition's block device path, e.g. /dev/sdc1>`

4. open gnome-files, go to `/media` and right-click on all the iso mounted folders and unmount them. (these are the source medias a.k.a the iso's being mounted after trying so many times from the woeusb gui)

5. then do this: `sudo woeusb --device /path/to/image.iso /dev/sdb --tgt-fs NTFS --verbose` (https://github.com/slacka/WoeUSB/issues/30#issuecomment-365730519)

**Comment by Hellseher** [comment]
Stabled with the same problem:

- un-unmount WINDOWS.ISO, if mounted: `sudo umount /dev/loopX`
- un-mount TARGET device if mounted: `sudo umount /dev/sdX[1-9]`
- remove all partitions from TARGET device, if exist: 'sudo dd if=/dev/zero of=/dev/sdX bs=512 count=1 conv=notrunc`
- use CLI to "burn" WINDOWS.ISO -> TARGET:  `sudo woeusb /path/to/windows.iso /dev/sdX`

**Comment by emgyrz** [comment]
I tried all the methods, spent a couple of hours. and the problem was not in woeusb! There was no loop device support in my kernel. When added, everything worked perfectly - `CONFIG_BLK_DEV_LOOP`

**Comment by Hritik14** [comment]
I had the same problem. Turns out some media was mounted on `/media/woeusb_source_*`.  (Run `mount` to check).     
Unmounting the source did the trick. It might have been there due to some previous writes by woeusb.

**Comment by mjakebarrington** [comment]
It should work if you go to files -> drive -> unmount. If that doesn't work format your drive (everyone is saying NTFS but FAT seemed to work for my drive) and try that process again.

**Comment by mumma-quincy** [comment]
Go to Disks -> on top right select format disk -> start woeusb -> select as ntfs -> burn iso

**Comment by WictorT** [comment]
What I ended up doing is going to `sudo nautilus` and ejecting all the drives that start with `woe*`. It seems like WoeUSB creates virtual drives for him to use and after something fails it forgets to remove them.

**Comment by xorb** [comment]
> What I ended up doing is going to `sudo nautilus` and ejecting all the drives that start with `woe*`. It seems like WoeUSB creates virtual drives for him to use and after something fails it forgets to remove them.

I did work for me, however I had to umount "efi" and "my_usb" instead.

**Comment by vitormm** [comment]
> For anyone that are affected by this issue, please check out https://github.com/slacka/WoeUSB/wiki/F.A.Q.#why-does-woeusb-cant-find-my-external-usb-drive-after-i-use-the-eject-button-in-filemanager-etc-to-unmount-its-filesystems if the method mentioned there can solve your problem.

Solved my problem! Thanks

**Comment by M0Rph3U56031769** [comment]
> Man, all you need is use Gparted to format your usb (the partition you want to mount ISO file on). After that, just do the process again with Woeusb, you're gonna see the magic happens

 all you need is use Gparted -> nautilus has also this feature. don't need gparted for this

**Comment by fatihayyildiz** [comment]
> I have the same issue, woeusb always shows error code 256, I solved by this:
> Go to Disks,
> ![disks](https://user-images.githubusercontent.com/22439269/55854947-bf4f4f00-5b83-11e9-9c50-f3c31f660b16.png)
> And Unmount your USB,
> And then create USB using woeusb, It's working now.

This is working for me. You need to unmount from disk management, then everything works fine. Unmounting or ejecting from file explorer didn't help

**Comment by zacharyrgonzales** [comment]
What helped me was formatting the usb as fat, then reopening woeusb, selecting "ntsf" then selecting "install" to create a win10 usb.

**Comment by Kashif1Naqvi** [comment]
I have also same issue when try to boot show me same error mentioned in question 
so firstly I type in terminal
sudo umount /dev/sdb1              // my usb path
then again restart 
using radio button select nstf option then install then working for me

**Comment by Mennaruuk** [comment]
> I used FAT but did not work, then I used NTFS and worked great, so I think the format matters.

This advice helped me out. I already made a Fedora USB, so for some reason WoeUSB couldn't format that on its own. I had to format it by going to Disks then formatting as NTSF. After that, I went back to WoeUSB, refreshed, chose the flash drive, and boom, it worked. Thanks!

**Comment by gilbertoalbino** [comment]
If you plug the pendrive, it says: "UNMOUNT", then you unmount, and it says: "IT'S NOT MOUNTED"
What's the trick here?
Is this piece of software a joke? easter egg?

**Comment by jesserbassett** [comment]
Hey all,
All you need to do is uninstall woeusb. There's a better tool altogether-Woeusb-ng. Google it and find out for yourselves. It fixes the many problems with WOEUSB.

**Comment by gilbertoalbino** [comment]
> Hey all,
> All you need to do is uninstall woeusb. There's a better tool altogether-Woeusb-ng. Google it and find out for yourselves. It fixes the many problems with WOEUSB.

Thanks!

**Comment by janto** [comment]
Just to repeat the advice given in this thread, this sequence worked for me
1. make sure the source file is not mounted (argh!) due to previous runs of woeusbgui (look in Disks)
2. format usb with gparted as ntfs
3. `umount /dev/sdb` ..Nautilus' unmount might unmount the entire device and not just filesystem
4. `sudo ./woeusb-5.0.4.bash --device Win10_20H2_v2_English_x64.iso /dev/sdb --target-filesystem NTFS`

I had to do all these to get it to work. Thanks everyone!

**Comment by JR2Media** [comment]
> I've faced with the same problem:
> 
> **Make sure list**
> 
>     * un-unmount WINDOWS.ISO, if mounted. ISO file is usually mounted to loop device: `sudo umount /dev/loopX`
> 
>     * un-mount TARGET device if mounted: `sudo umount /dev/sdX[1-9]`
> 
>     * remove all partitions from TARGET device, if exist: `sudo dd if=/dev/zero of=/dev/sdX bs=512 count=1 conv=notrunc`
> 
>     * use CLI to "burn" WINDOWS.ISO -> TARGET:  `sudo woeusb /path/to/windows.iso /dev/sdX`

This solved it!

I had the WIndows ISO mounted. Be sure to unmount the ISO if you have it mounted. I almost gave up.

**Comment by JR2Media** [comment]
Actually it didn't work. I get another error. I solved it by creating a Windows ISO on a Windows machine.

**Comment by doorz1009** [comment]
@Lin-Buo-Ren I may recommend slightly reworking the error string to include what device is currently still mounted to clarify to the user what device is causing problems. I thought my problem was that my usb's partition was mounted (though I unmounted it and knew it was unmounted) but the problem was that the iso was still mounted.

**Comment by Lin-Buo-Ren** [comment]
> @Lin-Buo-Ren I may recommend slightly reworking the error string to include what device is currently still mounted to clarify to the user what device is causing problems. I thought my problem was that my usb's partition was mounted (though I unmounted it and knew it was unmounted) but the problem was that the iso was still mounted.

I've tracked this particular issue at [Improve "filesystem still mounted" error message · Issue #45 · WoeUSB/WoeUSB](https://github.com/WoeUSB/WoeUSB/issues/45)

**Comment by faisalurrehman234** [comment]
> Installation failed !
> Exit code: 256
> Log:
> WARNING: The deprecated --format option is still available but will be dropped in WoeUSB v3.0!
> Error: Target device is currently busy, unmount all mounted partitions in target device then try again
> Target device is busy, please make sure you unmount all filesystems on target device before detaching it.
> 
> OS: Zorin OS.

Type disks and select your usb drive.
and click on psuse/resume button inside menu to unmount all partitions of USB Drive.
Now you can continue woe-usb.
It worked for me.

**Comment by Mantra27** [comment]
Unmount the ios image you mounted before, and try again. I dont think you need to unmount the usb drive

**Comment by David-T7** [comment]
> None of the above-mentioned solutions worked for me. I used the command line tool with this command `sudo woeusb --device Win10_Image.iso /dev/sda --tgt-fs NTFS`. Working great.

tnx man for posting this it worked for me.

**Comment by ivanjermakov** [comment]
For me the problem was the automounting daemon (`udevil` in my case)

**Comment by Saugatkafley** [comment]
I unmount the iso file , then only worked !

**Comment by MnAkash** [comment]
> Just FYI for anyone who stumbles here. I was getting this error, but when I unmount the drive, it didn't show up in WoeUSB anymore. The fix was to format the USB drive. I used NTFS, but don't know if that matters. After that everything worked great.

In mt case there was a hidden FAT partition on USB drive, so formatting to NTFS was not solving the issue. Deleting all partition and formatting again to NTFS solved the issue.

**Comment by kavania2002** [comment]
I also had this same problem but after formatting in NFTS format, it's working completely fine.
