### ISSUE TITLE
System lagging while copying data

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [slacka/WoeUSB#113]
## Good Habit Checklist for Issue Reporting
Checkout [Mastering Markdown · GitHub Guides](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) if you needs help on the Markdown syntax.

* [x] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed.
* [x] I've built the latest development snapshot using the instructions in README and verified that the issue can still be reproduced (for bug reports)

## NOTE
Probably hardware/firmware/driver dependent, please comment if you can/can't reproduce it, thanks!

Maybe related to #98 

## Issue Reproduce Instructions
1. Run WoeUSB either by GUI or CLI
1. Start partition or device installing

## Expected Behavior
* Mouse doesn't lags during installation

## Current Behavior
* Mouse lags harshly during installation, music playing become choppy.
* After installation everything back to normal

### WoeUSB Version
Happens on every version >= 2.0.0, it is also noticed <2.0.0, as well, but not sure the exact versions affected by this issue

### OS Distribution
KDE Neon(based on ubuntu) 5.10 AMD64

### OS Kernel
Linux 4.8.0-54-generic from Ubuntu 16.04 software archive

### Primary Memory Size
8GiB

### Model Name of Target Device
Transcend JetFlash® 790K(`lsblk` says "Transcend 64GB") 64GB (USB 3.1 variant)

### Connection of Target Device
USB 3.0 port via intel native USB controller

### Computer Model
ASUS S550CB

### Source Media Info
Any should do

**Comment by madleech** [comment]
Happens to me too. Are you running a 64bit kernel? If so this explains the problem: https://lwn.net/Articles/572911/

More discussion here: https://unix.stackexchange.com/questions/107703/why-is-my-pc-freezing-while-im-copying-a-file-to-a-pendrive

**Comment by JonnyTech** [comment]
@Lin-Buo-Ren: Try using the [nice](http://www.unix.com/man-page/linux/1/nice/) / renice command to set / adjust the process priority:

`
nice -n -20 cp "${source_file}" "${dest_file}"
`

**Comment by JonnyTech** [comment]
@Lin-Buo-Ren: Thinking about it, [ionice](http://www.unix.com/man-page/linux/1/ionice/) is better suited for I/O type process like cp:

`
ionice -c 2 -n 0 cp "${source_file}" "${dest_file}"
`

**Comment by Lin-Buo-Ren** [comment]
@madleech Thanks for the info!  We might be able to mitigate this issue by tweaking vm parameters.

@JonnyTech Thanks for your suggestion, but it's seems that the cause @madleech point out may not be mitigate by `ionice`, maybe I'm wrong though...

**Comment by Lin-Buo-Ren** [comment]
Think again it might be better to tweak the mount option of the target filesystem and add `sync` to it may solve the problem.
Don't modify vm parameters as it will also affect other storage I/O.n

**Comment by i3wm** [comment]
@Lin-Buo-Ren Doesn't lag in my PC.

**Additional info**:
---
**WoeUSB version**
Latest compiled from git

**OS Distribution**
ArchLinux [i3wm] 64 bit

**OS Kernel**
Linux arch 4.11.9-1-ARCH

**Model Name of Target Device**
Transcend TS4GJF500 4GB

**Connection of Target Device**
USB 2.0 - Linux Foundation 2.0 root hub

**Computer model**
Acer ES1 572

**Source Media Info**
Any should do

**Comment by Lin-Buo-Ren** [comment]
@ i3wm 
Thanks for your feedback!  However your target device info doesn't seems to be an USB device but a root hub, please provide the required information by running `lsblk --output=MODEL --nodeps --output MODEL <target device file>` (e.g. `lsblk --output=MODEL --nodep
MODEL /dev/sda`)

**Comment by Lin-Buo-Ren** [comment]
I've tried the `sync` mount option and noticed that the lags gone, however I still need to know if it affects the install time.

**Comment by Lin-Buo-Ren** [comment]
Bad news: The `sync` options greatly affects the install time to over 10 minutes, so this solution doesn't work.  I might make a comparison in the near future.

**Comment by Lin-Buo-Ren** [comment]
@i3wm Would you like to share the amount of your system's primary memory(e.g. RAM)?  According to the research the issue doesn't affect systems with small system memory.

**Comment by i3wm** [comment]
@Lin-Buo-Ren **RAM**: 4 GB
