### ISSUE TITLE
configure doesn't check if webkitgtk is available

### ISSUE THREAD

**Issue by salvadorp2001** [slacka/WoeUSB#114]
## Issue Reproduce Instructions
1. Attempt to compile without webkitgtk2 installed

## Expected Behavior
Correct compilation

## Current Behavior
Make fails with errors about ld not finding ```libwebkitgtk-1.0.so.0```

## OS Distribution
Arch Linux

## Fix
Install webkitgtk2 from pacman. Although I'm not sure WoeUSB really needs webkitgtk.

**Comment by Lin-Buo-Ren** [comment]
AFAICS we don't use webkitgtk2, maybe is its dependency?

**Comment by Lin-Buo-Ren** [comment]
We pretty much solely uses WxWidgets for our GUI implementation, so if there's any dependency issue about the GUI it should be in WxWidgets but not us.
