### ISSUE TITLE
Error: Unable to mount source media

### ISSUE THREAD

**Issue by borbaszorbas** [slacka/WoeUSB#138]
running woeusb-git r486.57a510b-2 from aur currently on Antergos  OS. 
When trying to make a windows 10 64-bit usb i get the following error:

```
$ sudo woeusb --device Win10_1607_English_x64.iso /dev/sdc -v
trap_return: INFO: returning from process_commandline_parameters
determine_target_parameters: Info: Target device is '/dev/sdc'.
determine_target_parameters: Info: Target partition is '/dev/sdc1'.
Overwriting "/dev/sdc"'s partition table...
Wait 3 seconds for block device nodes to populate...
mkfs.fat 4.1 (2017-01-24)
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
Mounting source filesystem...
mount: /media/woeusb_source_1505827640_26791: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
mount_source_filesystem: Error: Unable to mount source media
Error: Unable to mount source filesystem
Unmounting and removing '/media/woeusb_source_1505827640_26791'...
umount: /media/woeusb_source_1505827640_26791: not mounted.
cleanup_mountpoints: Warning: Unable to unmount source filesystem.
Some mountpoints are not unmount/cleaned successfully and must be done manually
You may now safely detach the target device
```

(modified by @Lin-Buo-Ren : Fix preformatted text markup)

**Comment by JonnyTech** [comment]
I suspect that your Windows ISO file is corrupt. Download again and verify the checksum.

**Comment by Lin-Buo-Ren** [comment]
Hello, please provide the generated system log during the filesystem mount attempt.  The following instructions should do:

1. Open a terminal emulator application
1. Run `journalctl --follow --lines=0 &` command
1. Reproduce your issue
1. Run `kill %1`
1. Copy & paste the printed messages between `journalctl` and `kill`

**Comment by borbaszorbas** [comment]
Guys I was just  dumb and the windows iso was corrupt as marked by JonnyTech. Sorry to open an Issue for such a stupid thing

**Comment by UlisseMini** [comment]
I have this problem too, I have downloaded the windows ISO twice, they have the same checksum and I cannot for the life of me find where on their website they provide the checksums.

**Comment by hinteor** [comment]
i have this problem too
`фев 16 23:51:09 wyvern-laptop kwin_x11[1816]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 20035, resource id: 79700669, major code: 15 (QueryTree), minor code: 0
фев 16 23:51:09 wyvern-laptop kwin_x11[1816]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 20039, resource id: 79700669, major code: 18 (ChangeProperty), minor code: 0
фев 16 23:51:10 wyvern-laptop kwin_x11[1816]: file:///usr/share/kwin/aurorae/MenuButton.qml:22: TypeError: Cannot read property 'closeOnDoubleClickOnMenu' of null
фев 16 23:51:10 wyvern-laptop kwin_x11[1816]: file:///usr/share/kwin/aurorae/MenuButton.qml:22: TypeError: Cannot read property 'closeOnDoubleClickOnMenu' of null
фев 16 23:51:10 wyvern-laptop kwin_x11[1816]: file:///usr/share/kwin/aurorae/MenuButton.qml:22: TypeError: Cannot read property 'closeOnDoubleClickOnMenu' of null
фев 16 23:51:10 wyvern-laptop kwin_x11[1816]: file:///usr/share/kwin/aurorae/MenuButton.qml:22: TypeError: Cannot read property 'closeOnDoubleClickOnMenu' of null
фев 16 23:51:10 wyvern-laptop pkexec[10042]: pam_unix(polkit-1:session): session opened for user root by hinteor(uid=0)
фев 16 23:51:10 wyvern-laptop audit[10042]: USER_START pid=10042 uid=0 auid=1000 ses=2 msg='op=PAM:session_open grantors=pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/pkexec" hostname=wyvern-laptop addr=? terminal=pts/2 res=success'
фев 16 23:51:10 wyvern-laptop kwin_x11[1816]: file:///usr/share/kwin/aurorae/MenuButton.qml:22: TypeError: Cannot read property 'closeOnDoubleClickOnMenu' of null
фев 16 23:51:10 wyvern-laptop kernel: audit: type=1105 audit(1581875470.395:644): pid=10042 uid=0 auid=1000 ses=2 msg='op=PAM:session_open grantors=pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/pkexec" hostname=wyvern-laptop addr=? terminal=pts/2 res=success'
фев 16 23:51:10 wyvern-laptop pkexec[10042]: root: Executing command [USER=root] [TTY=/dev/pts/2] [CWD=/home/hinteor/Загрузки] [COMMAND=/usr/bin/sh -c woeusb --no-color --for-gui --target-filesystem FAT --device "/home/hinteor/Загрузки/Win10_1909_Russian_x64.iso" "/dev/sdb" 2>&1]
фев 16 23:51:10 wyvern-laptop kwin_x11[1816]: file:///usr/share/kwin/aurorae/MenuButton.qml:22: TypeError: Cannot read property 'closeOnDoubleClickOnMenu' of null
фев 16 23:51:10 wyvern-laptop kwin_x11[1816]: file:///usr/share/kwin/aurorae/MenuButton.qml:22: TypeError: Cannot read property 'closeOnDoubleClickOnMenu' of null
фев 16 23:51:10 wyvern-laptop kwin_x11[1816]: file:///usr/share/kwin/aurorae/MenuButton.qml:22: TypeError: Cannot read property 'closeOnDoubleClickOnMenu' of null
фев 16 23:51:10 wyvern-laptop kwin_x11[1816]: file:///usr/share/kwin/aurorae/MenuButton.qml:22: TypeError: Cannot read property 'closeOnDoubleClickOnMenu' of null
фев 16 23:51:10 wyvern-laptop kwin_x11[1816]: file:///usr/share/kwin/aurorae/MenuButton.qml:22: TypeError: Cannot read property 'closeOnDoubleClickOnMenu' of null
фев 16 23:51:12 wyvern-laptop kwin_x11[1816]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 21701, resource id: 79701985, major code: 15 (QueryTree), minor code: 0
фев 16 23:51:12 wyvern-laptop kwin_x11[1816]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 21705, resource id: 79701985, major code: 18 (ChangeProperty), minor code: 0
`
