### ISSUE TITLE
dpkg-buildpackage -uc -b failure in Debian stretch

### ISSUE THREAD

**Issue by 4joey1** [slacka/WoeUSB#160]
Hi!I have installed Debian 9 stretch 64 bit and I wanted to create a bootable USB from a Windows 7 iso and was hoping to use woeUSB.

I downloaded both the WoeUSB-3.1.4.zip  and woeusb-build-deps_3.1.4_all.deb  package from link below 

https://github.com/slacka/WoeUSB/releases  

Referring to the README.md file that I found in the zip, I next proceeded to Install WoeUSB's Build Dependencies as below

# sudo apt-get install devscripts equivs gdebi-core #This command ran well with no errors

# mk-build-deps  --The command failed with errors below
mk-build-deps: warning:     debian/changelog(l1): version '@@WOEUSB_VERSION@@' is invalid: version number does not start with digit
LINE: woeusb (@@WOEUSB_VERSION@@) unstable; urgency=low
dh_testdir
dh_testroot
dh_prep
dh_testdir
dh_testroot
dh_install
dh_install: Compatibility levels before 9 are deprecated (level 7 in use)
dh_installdocs
dh_installdocs: Compatibility levels before 9 are deprecated (level 7 in use)
dh_installchangelogs
dpkg-parsechangelog: warning:     debian/changelog(l1): version 'unknown' is invalid: version number does not start with digit
LINE: woeusb-build-deps (unknown) unstable; urgency=low
dh_compress
dh_fixperms
dh_installdeb
dh_installdeb: Compatibility levels before 9 are deprecated (level 7 in use)
dh_gencontrol
dpkg-gencontrol: warning:     debian/changelog(l1): version 'unknown' is invalid: version number does not start with digit
LINE: woeusb-build-deps (unknown) unstable; urgency=low
dpkg-gencontrol: error: invalid source version unknown
dh_gencontrol: dpkg-gencontrol -pwoeusb-build-deps -ldebian/changelog -Tdebian/woeusb-build-deps.substvars -Pdebian/woeusb-build-deps returned exit code 255
debian/rules:20: recipe for target 'binary-indep' failed
make: *** [binary-indep] Error 2
Error in the build process: exit status 2

Once the above failed,I tried using the woeusb-build-deps_3.1.4_all.deb that I had downloaded as explained earlier and ran command below which ran successfully with no errors

# sudo gdebi woeusb-build-deps_3.1.4_all.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done

build-dependencies for woeusb
 Depencency package to build the 'woeusb' package
Do you want to install the software package? [y/N]:y
(Reading database ... 228872 files and directories currently installed.)
Preparing to unpack woeusb-build-deps_3.1.4_all.deb ...
Unpacking woeusb-build-deps (3.1.4) over (3.1.4) ...
Setting up woeusb-build-deps (3.1.4) ...

When I tried building the woeUSB deb package with command below I got following errors

# dpkg-buildpackage -uc -b
dpkg-buildpackage: warning:     debian/changelog(l1): version '@@WOEUSB_VERSION@@' is invalid: version number does not start with digit
LINE: woeusb (@@WOEUSB_VERSION@@) unstable; urgency=low
dpkg-buildpackage: info: source package woeusb
dpkg-buildpackage: info: source version unknown
dpkg-buildpackage: error: version number does not start with digit

Kindly assist in resolving this.Thanks in advance.

**Comment by 4joey1** [comment]
After dpkg-buildpackage -uc -b failed I tried using the generic method below and all commands ran successfully

$ autoreconf --force --install 
$ ./configure
$ make
$ sudo make install

However when I launch woeUSB and select both the ISO,the USB drive and click Install I get the error message below

Installation failed!
Exit code: 32512
Log:
/bin/sh: 1: woeusb: not found

**Comment by Lin-Buo-Ren** [comment]
Hello, currently we don't support building with the zip archive in the releases page(which is hinted with the file `The.source.code.archives.provided.here.is.NOT.supported.please.use.git-clone.instead`.

You have to clone the repository using Git, then refer the [Setting the Application Version String](https://github.com/slacka/WoeUSB#setting-the-application-version-string) section to set the proper package version.

**Comment by Lin-Buo-Ren** [comment]
>/bin/sh: 1: woeusb: not found

Please run and report the output of `which woeusb` and `printenv | grep ^PATH=` command in a text terminal.

**Comment by 4joey1** [comment]
Find output below

# which woeusb
/usr/local/bin/woeusb
# printenv | grep ^PATH=
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by Lin-Buo-Ren** [comment]
Report the following output then: `sudo 'sh -c "printenv | grep ^PATH="'`

**Comment by 4joey1** [comment]
Also note error below when  Setting the Application Version String

# ./setup-development-environment.bash
Setting Project-specific Git configuration...fatal: not in a git directory
Activate Git smudge filter...
rm: cannot remove '.git/index': No such file or directory
An error occurred at line number 66 and the script is prematurely aborted

**Comment by Lin-Buo-Ren** [comment]
You *must* use the Git repository instead of the source archive in order to let the /setup-development-environment.bash program work

**Comment by Lin-Buo-Ren** [comment]
Also as a workaround you should use the `woeusb` command instead of the GUI

**Comment by 4joey1** [comment]
Thanks so much  @Lin-Buo-Ren .I have installed woeUSB from the git repository and was able to create a bootable Windows USB and installed Windows on another machine.
