### ISSUE TITLE
Building from source on Ubuntu 16.04: Dependency is not satifisable: debhelper (>= 10)

### ISSUE THREAD

**Issue by michaelhochleitner** [slacka/WoeUSB#161]
* [X] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed
* [X] I've built the latest development snapshot using the instructions in README and verified that the issue can still be reproduced (for bug reports)

## Issue Reproduce Instructions
> 1. git clone https://<span></span>github.com/slacka/WoeUSB.git
> 2. cd WoeUSB/
> 3. git checkout v3.1.4
> 4. ./setup-development-environment.bash
Output:
Activate Git smudge filter...
smudge-version: DEBUG: Use v3.1.4 as this version's tag
DEBUG: smudge-version is done
smudge-version: DEBUG: Use v3.1.4 as this version's tag
DEBUG: smudge-version is done
smudge-version: DEBUG: Use v3.1.4 as this version's tag
DEBUG: smudge-version is done
smudge-version: DEBUG: Use v3.1.4 as this version's tag
DEBUG: smudge-version is done
smudge-version: DEBUG: Use v3.1.4 as this version's tag
DEBUG: smudge-version is done
done.
> 5. sudo apt-get install devscripts equivs gdebi-core
> 6. mk-build-deps
> 7. sudo gdebi woeusb-build-deps_3.1.4_all.deb

## Expected Behavior
> No error

## Current Behavior
> Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: debhelper (>= 10)

### WoeUSB Version
> v3.1.4

### WoeUSB Source
> Built from source code, commit fa36514

### GNU Bash Version
> GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)

### Information about the Operating System
> Description:    Ubuntu 16.04.3 LTS

**Comment by Lin-Buo-Ren** [comment]
Hello, currently WoeUSB follows the latest debhelper version which is not existed in Ubuntu 16.04 for policy compliance reasons.  Manually edit the debian/control file and reduce the version to 9 and retry the build should work.
