### ISSUE TITLE
processManager.cpp:70: simple file handling error

### ISSUE THREAD

**Issue by dcb314** [slacka/WoeUSB#162]
processManager.cpp:70]: (warning) Storing fgetc() return value in char variable and then comparing with EOF.

Source code is

   char letter = '\0';
  ...
       else if(letter == EOF)

Suggest that type of letter be changed from char to int.

**Comment by Lin-Buo-Ren** [comment]
Thanks for your suggestion!  Will look into it soon.

**Comment by dcb314** [comment]
>You can convert the variable 'letter' explicitly to an int just for the comparison. 

You can do that, but it won't achieve what you want.

See http://c-faq.com/stdio/getcharc.html for more details.

or page 16 in K & R 2, the standard book of the language.

**Comment by Skrilltrax** [comment]
@dcb314 thanks, i just realized fgetc returns an int to accomodate for the EOF character.
I'll just change the pull request or you can create one since you originally solved the issue.

**Comment by dcb314** [comment]
>I'll just change the pull request 

Yes, please.

**Comment by Lin-Buo-Ren** [comment]
The fix is merged now, apologies for the long ignorance.
