### ISSUE TITLE
woeusbgui did not set the Boot flag on the FAT32 partition it created

### ISSUE THREAD

**Issue by anthonyfok** [slacka/WoeUSB#170]
* [x] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed
* [x] I've built the latest development snapshot using the instructions in README and verified that the issue can still be reproduced (for bug reports)

## Issue Reproduce Instructions
> 1. `git clone https://github.com/slacka/WoeUSB.git`
> 2. `cd WoeUSB`
> 3. `vim debian/changelog` and changed `@@WOEUSB_VERSION@@` to `3.1.4` (I know it is not right, but I was lazy and wanted a quick-and-dirty woeusb build, so I could use it to fix a desktop computer where the Windows partitions were moved for partition alignment after transferring the system from HDD to SSD.)
> 4. `sudo apt install libwxgtk3.0-dev` to fulfill build dependency
> 5. `debuild -us -uc`
> 6. `sudo dpkg -i ../woeusb_3.1.4_amd64.deb` (again, I know this has the wrong Debian version number, but again, I was lazy.)
> 7. Run `woeusbgui`
> 8. Select my Windows 10 Fall Creators Update image, and my USB drive on /dev/sdc
> 9. Click "Install"
> 10. Enter my password for authentication in the pop-up dialogue.
> 11. After woeusbgui finishes copying the Windows 10 ISO to the USB thumb drive, unplug it, then plug it into the target computer, and turn on that computer.

## Expected Behavior
> The created USB drive would boot up Windows 10 Fall Creators Update installation.

## Current Behavior
> The created USB drive was totally ignored during boot up.  It turns out that the boot flag was missing.
> Fortunately, this was easily fixed by manually running `fdisk /dev/sda` and pressing "a" to toggle a bootable flag, and "w" to write to the USB drive.  After that, the USB thumb drive was working.

### WoeUSB Version
> v3.1.4-15-g206c032-dirty

### WoeUSB Source
> Built from source code, commit 206c032

### GNU Bash Version
> GNU bash, version 4.4.18(1)-release (x86_64-pc-linux-gnu)

### Information about the Operating System
> Debian GNU/Linux unstable (sid), running GNOME 3.28

### Information about the Source Media
> "Windows 10 Fall Creators Update ISO" downloaded from <https://www.microsoft.com/en-ca/software-download/windows10ISO>

### Information about the Target Device
> SanDisk Ultra USB 3.0 Flash Drive, 32GB (SDCZ48-032G-CC64T)

**Comment by anthonyfok** [comment]
I guess what would be nice too is for `woeusbgui` to produce some kind of a log file, or maybe "Details" which the end users could expand and see and possibly copy-and-paste or even save to file.

(Please correct me if I am wrong... I haven't looked at WoeUSB or its GUI equivalent closely enough yet, so it might already have this feature already.)

**Comment by Vdragon** [comment]
Thanks for your extensive report, however this is considered to be a firmware bug instead of WoeUSB's bug, refer issue #97 for more details.

Currently `woeusbgui` only displays log when error is occurred, you may file a separate issue to make it visible in other form.

**Comment by anthonyfok** [comment]
What!?  A firmware bug?  As in a BIOS bug?  Are you kidding me?
I was creating a Windows USB bootdisk, and it does NOT use GRUB, so setting the bootflag is required.

If a Windows-created bootable USB medium can boot, but WoeUSB cannot, then it is WoeUSB's bug.  It is as simple as that.

It is a simple bug that can be fixed by toggling the boot flag of the appropriate partition, so 何樂而不為？
Are you trying to be philosophical or purist or something?

**Comment by anthonyfok** [comment]
> I was creating a Windows USB bootdisk, and it does NOT use GRUB...

I stand corrected, as I realized WoeUSB does use GRUB to do its magic, but anyhow:

If you call the way legacy BIOS detects bootable device a "firmware bug", then there are a WHOLE lot of buggy devices out there.

Check out _any_ Linux distributions.  Just about all of them use GRUB, right?
Can you find any x86 Linux distribution which decides that, since GRUB does not need a bootable flag, intentionally NOT set any bootable flag on any partition, and a bunch of users complain that their new Linux installation wouldn't even boot up, and the developers respond, "Oh, sorry your firmware is buggy.  GRUB doesn't need it, so we really shouldn't add a bootable flag."

If you can find just ONE example like that, I will rest my case.

**Comment by anthonyfok** [comment]
Hi again @Lin-Buo-Ren,

I like your fix in https://github.com/slacka/WoeUSB/commit/77dc615f1c2584b494d9804371b72972f5a72b40, as in it gives the end user a choice, but I highly recommend that you turn it around, i.e., make it an "opt-out" rather than "opt-in", i.e., enable `--workaround-bios-boot-flag` by default, and if the end user really really does not want it, he/she can use, for example, `--do-not-workaround-bios-boot-flag` to disable the bootflag.

I know that it is _not_ WinUSB/WoeUSB's fault that many legacy computer BIOSes purposefully checks for the bootable flag and would just ignore that device if it couldn't find it, but, unfortunately, that was how they were designed.

預設開啟 boot flag，有什麼問題嗎？會導致 UEFI 或 non-buggy BIOS 系統開不了機嗎？

無論是誰的錯，終端使用者是無辜的。為了堅持某種原則，搞得使用舊電腦的使用者莫名其妙，何苦呢？

WoeUSB CLI  還好，有個 `--workaround-bios-boot-flag` （雖然大部分使用者未必注意到。）

WoeUSB GUI 就慘了，連選擇的機會都沒有，而且 WoeUSB GUI 的目標使用者不是「菜鳥級」的嗎？不一定懂得用 fdisk，製作出來的 USB 大姆哥就是死活開不了機，您說他們除了哭笑不得，或罵 WoeUSB 或罵 Linux，還能怎麼樣？算了，Linux 的軟體，open-source 軟體就是不行，還是使用 Microsoft 的 Windows 10 media creation tool 吧……

既然如此，當初何苦寫了個 GUI？
