### ISSUE TITLE
Windows cannot install to GPT drive

### ISSUE THREAD

**Issue by JonnyTech** [slacka/WoeUSB#177]
I have just built the latest woeusb from source and used it to make a bootable drive:

```
$ woeusb -V
/usr/local/bin/woeusb: line 433: local: warning: only_for_gui_ref: circular name reference
/usr/local/bin/woeusb: line 433: warning: only_for_gui_ref: circular name reference
@@WOEUSB_VERSION@@

$ sudo woeusb -d en_w_7_AIO_x86x64_March_2018.iso /dev/sdb
```

The drive created is MBR, not GPT, is there any way to force it to boot UEFI?

When the Windows installer starts and I select a partition for installation, the Windows installer says that it cannot install there because it is a GPT drive. So I need the USB to boot in UEFI mode to install to that partition.

**Comment by Lin-Buo-Ren** [comment]
UEFI supports booting from MBR style partition table drives, what the Windows Installer complains is that your system installation target drives uses GPT but you've booted the MBR installer drive using legacy PC booting but not native UEFI booting.  Please ensure you've boot the installer drive in native UEFI booting scheme.

**Comment by Lin-Buo-Ren** [comment]
Please comment if you need any assistance in booting the Windows installation drive.

**Comment by MRolandd** [comment]
> UEFI supports booting from MBR style partition table drives, what the Windows Installer complains is that your system installation target drives uses GPT but you've booted the installer drive using legacy PC booting but not native UEFI booting, which is unsupported by Windows. Please ensure you've booted the installer drive in native UEFI booting scheme.

And how do you make the usb bootable in UEFI? WoeUSB doesn't let me choose between MBR and GPT. It chooses automatically MBR. And I haven't found any other tools for linux to make a  bootable USB with GPT
