### ISSUE TITLE
warning: only_for_gui_ref: circular name reference

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [slacka/WoeUSB#178]
## Good Habit Checklist for Issue Reporting
Checkout [Mastering Markdown · GitHub Guides](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) if you needs help on the GitHub-flavored Markdown syntax.  You may remove sections and contents that don't apply.

* [x] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed
* [ ] I've built the latest development snapshot using the instructions in README and verified that the issue can still be reproduced (for bug reports)

It is being continuously reported for a circular name reference in `only_for_gui_ref` parameter(#164, #177), some research must be done to ensure whether this is fixable in WoeUSB.

**Comment by ineeve** [comment]
I am using Ubuntu 17.10 and I have the same warning.

**Comment by Lin-Buo-Ren** [comment]
This bug is finally picked out from WoeUSB, cheers.
