### ISSUE TITLE
Cannot download woeusb on ubuntu 18.04

### ISSUE THREAD

**Issue by kuba-chledowski** [slacka/WoeUSB#188]
I am not able to install woeusb on ubuntu 18.04 - when i try  `sudo add-apt-repository ppa:nilarimogard/webupd8`,  I get this error:

```
Err:7 http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu bionic Release                                                                                               
  404  Not Found [IP: 91.189.95.83 80]
...            
Reading package lists... Done                                                       
E: The repository 'http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```
Any idea how can I fix that? I would like to make a windows 10 usb stick for dual boot.

Thanks! :)

**Comment by Lin-Buo-Ren** [comment]
The availability of the third party packages depend on their maintainer, contact WebUpd8 for assistance.

You may also:

* Try to build one from the source code, referring the [README](https://github.com/slacka/WoeUSB) for help
* Download the [standalone `woeusb` script](https://github.com/slacka/WoeUSB/blob/master/src/woeusb) and run it in the terminal directly(you have to install the runtime dependencies manually)

**Comment by Lin-Buo-Ren** [comment]
Feel free to request further assistance on getting `woeusb` via official channels.
