### ISSUE TITLE
debian 8 no bootmgr

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [slacka/WoeUSB#201]
tried to make a bootable usb with windows 8.1 but i get bootmgr not found.. searched for issues but i didnt find anything similar

**Comment by Lin-Buo-Ren** [comment]
![screenshot_20180809_040221](https://user-images.githubusercontent.com/13408130/43861311-07e49510-9b89-11e8-96e9-86a90b45d44e.png)

Please be sure that the BOOTMGR file existed in the DVD image.  If the image isn't official the maker might have (un)intentionally stripped it.

**Comment by Lin-Buo-Ren** [comment]
Closing as it appears to be a problem with the source image.
