### ISSUE TITLE
Failure on disk images with spaces in their filenames.

### ISSUE THREAD

**Issue by NickSto** [slacka/WoeUSB#206]
## Description

Sorry, I haven't had time to install the development version. But since I didn't see this issue in the tracker, I thought I'd put it in as an FYI.

Basically, I tried putting an iso on a USB drive. The iso filename had spaces in it:
`Windows 10 [down 2018-09-11] [name Win10_1803_English_x64].iso`
WoeUSB kept giving an error about the source media being currently mounted (exit code 256). But the moment I renamed the iso file to `Win10_1803_English_x64.iso`, it worked.

It'd be great if it could handle spaces in filenames, but at least you could maybe check for that scenario and give an appropriate warning.

Thanks for all your work on this tool!

## Good Habit Checklist for Issue Reporting
Checkout [Mastering Markdown · GitHub Guides](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) if you needs help on the GitHub-flavored Markdown syntax.  You may remove sections and contents that don't apply.

* [x] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed
* [ ] I've built the latest development snapshot using the instructions in README and verified that the issue can still be reproduced (for bug reports)

## Issue Reproduce Instructions
`$ sudo woeusb -v -d ~/backuphide/isos/Windows\ 10\ \[down\ 2018-09-11\]\ \[name\ Win10_1803_English_x64\].iso /dev/sde`
It also occurs if you follow the normal steps in the GUI (Choose the iso file as the source disk image, choose the `/dev/sde` target device, hit Install, enter your password)

## Expected Behavior
It successfully installs the iso on the device

## Current Behavior
It issues a misleading error.
From the command line:
```
trap_return: INFO: returning from process_commandline_parameters
WoeUSB v@@WOEUSB_VERSION@@
==============================
determine_target_parameters: Info: Target device is '/dev/sde'.
determine_target_parameters: Info: Target partition is '/dev/sde1'.
grep: Invalid range end
Error: Source media is currently mounted, unmount the partition then try again
```
From the GUI:
```
Installation failed!
Exit code: 256
Log:
WoeUSB v@@WOEUSB_VERSION@@
==============================
grep: Invalid range end
Error: Source media is currently mounted, unmount the partition then try again
Target device is busy, please make sure you unmount all filesystems on target device or shutdown the computer before detaching it.
```

### WoeUSB Version
`3.2.2-1~webupd8~bionic0`

### WoeUSB Source
Installed from WebUpd8 PPA (`ppa:nilarimogard/webupd8`)

### GNU Bash Version
`4.4.19(1)-release (x86_64-pc-linux-gnu)`

### Information about the Operating System
Ubuntu 18.04.1 LTS

### Information about the Source Media
Windows 10 1803
sha256: `2a7e8c918347f36c23dcbab9804aca5b88eaf8b118c7356b1d96ab771ecb017f`

### Information about the Target Device
SanDisk Cruzer 8GB
Kanguru Flash BLU 30 8GB
(happened on both)

**Comment by Lin-Buo-Ren** [comment]
> It'd be great if it could handle spaces in filenames

In fact, filename interoperability is always a priority.  This is a bug, thanks for reporting!

**Comment by NickSto** [comment]
Hey! Thanks for such a quick reply.
Yeah, I actually saw that line, but I couldn't see how that'd cause the bug, so I figured it was somewhere else. But yep, the brackets would do it.
`grep -F` would fix it in GNU grep; can't confirm the portability of that, though.

**Comment by Lin-Buo-Ren** [comment]
It should be fixed now, as the core script is actually standalone you may directly download https://github.com/slacka/WoeUSB/blob/master/src/woeusb , add executable bit and run it in a terminal to verify if your issue is solved.

**Comment by suamor** [comment]
The above issue is not fixed. On Ubuntu 18.04.1 (where the version is displayed as WOE_VERSION, which is another issue, but package management says 3.2.10) the fix is in place but it still fails. The medium is not mounted. When I use the commands manually bash returns error code 0. Not sure why it is failing. I worked around by making the error a warning and still continue which worked fine.

**Comment by suamor** [comment]
`$ sudo woeusb --device Downloads/Windows_10_Reparaturdatentraeger_64_Bit.iso /dev/sdd`
`Error: Source media is currently mounted, unmount the partition then try again`

Not a problem of the program but the ISO does not boot anyway (BSOD), so it's not critical for me. But it would be good if there is no issue with a normal Ubuntu 18.04.1 ISO. Thanks

**Comment by hamid-m** [comment]
The issue mentioned by @suamor in the [comment](https://github.com/slacka/WoeUSB/issues/206#issuecomment-448541409) still is true for me.  Using Ubuntu 18.04.3, despite unmounting the USB drive, WoeUSB gave me the same error message.  
I had to remove the if-statement [here](https://github.com/slacka/WoeUSB/blob/master/src/woeusb#L916) in order to get the program to proceed.

**Comment by titulebolide** [comment]
Hello there! I did create a windows10 usb key from the official windows 10 iso released by microsoft (it was the file `Win10_1909_French_x64.iso`) and I had to use @hamid-m workaround to have it working. I pulled the latest commit of woeUSB to test it, so I suppose the issue is still pending...
I checked my image checksum and it was ok, so the issue is not coming from this iso...
Everything else worked flawlessly, thanks!

**Comment by yashnaman** [comment]
@titulebolide @hamid-m Could you binary which has those changes?

**Comment by hamid-m** [comment]
Sorry @yashnaman , I don't have a recollection of how the fix was implemented.  Perhaps I built the binaries as per the README, but I do not recall.

**Comment by yashnaman** [comment]
No problem. Thanks.

**Comment by rklasen** [comment]
I just encountered a similar bug. I also got the same error message. In my case, the ISO filename didn't include brackets nor whitespaces, but underscores. After removing them, the ISO falshed fine to a thumb drive.

**Comment by kolapkarayush** [comment]
Okay, I dont know what the error was but unmounting the usb solved it.
go in the terminal(ctrl+alt+t) and type the following commands-
df -h  (find your usb name for example /dev/sdb1);
then type-
sudo umount *your drive name*  (for me it was dev/sdb1)(so my syntax was sudo umount /dev/sdb1)

press refresh in woeusb and install again.
