### ISSUE TITLE
WoeUSB crashed due to improper parameter type assignment

### ISSUE THREAD

**Issue by thisaccountisforthisoneissue** [slacka/WoeUSB#207]
Installation failed!
Exit code: 256
Log:
WoeUSB v@@WOEUSB_VERSION@@
==============================
Mounting source filesystem...
Wiping all existing partition table and filesystem signatures in /dev/sdb...
/dev/sdb: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
/dev/sdb: calling ioctl to re-read partition table: Success
Ensure that /dev/sdb is really wiped...
Creating new partition table on /dev/sdb...
Creating target partition...
Making system realize that partition table has changed...
Wait 3 seconds for block device nodes to populate...
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
mkfs.fat 4.1 (2017-01-24)
Mounting target filesystem...
Applying workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
/usr/bin/woeusb: line 1348: true: unbound variable
Resetting workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
Unmounting and removing "/media/woeusb_source_1536893734_21674"...
Unmounting and removing "/media/woeusb_target_1536893734_21674"...
You may now safely detach the target device

I'm running Ubuntu 18.04 LTS
This is the second USB drive I've tried this with and the same error happens. I'm running the program as normal. I open the terminal umount the drive because otherwise it says "Drive is busy" then I open WoeUSB, select an .iso, select the usb drive, and then click install and then this happens every single time at the same exact spot.
I'm trying to install Windows 10 professional to the usb

**Comment by Walms** [comment]
Also getting this error. I tried setting the 3rd param to empty string, but then when the copy finished I just got lines upon lines of pules out in the terminal.

**Comment by Walms** [comment]
If you're looking for a workaround https://github.com/slacka/WoeUSB/releases 3.2.1 seems to work

**Comment by Lin-Buo-Ren** [comment]
Likely a regression, thanks for reporting!

**Comment by rephlex** [comment]
can totally reproduce:

`root@hera:/home/rephlex# woeusb -v --device Software/Win10_1803_German_x64.iso /dev/sdd
trap_return: INFO: returning from process_commandline_parameters
WoeUSB v@@WOEUSB_VERSION@@
==============================
determine_target_parameters: Info: Target device is '/dev/sdd'.
determine_target_parameters: Info: Target partition is '/dev/sdd1'.
Mounting source filesystem...
Wiping all existing partition table and filesystem signatures in /dev/sdd...
/dev/sdd: 2 Bytes wurden an Position 0x000001fe gelöscht (dos): 55 aa
/dev/sdd: ioctl wird aufgerufen, um die Partitionstabelle neu einzulesen: Erfolg
Ensure that /dev/sdd is really wiped...
Creating new partition table on /dev/sdd...
Creating target partition...
Making system realize that partition table has changed...
Wait 3 seconds for block device nodes to populate...
mkfs.fat 4.1 (2017-01-24)
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
Mounting target filesystem...
Applying workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
/usr/bin/woeusb: Zeile 1348: false ist nicht gesetzt.
Resetting workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
Unmounting and removing "/media/woeusb_source_1536911152_29429"...
Unmounting and removing "/media/woeusb_target_1536911152_29429"...
You may now safely detach the target device
root@hera:/home/rephlex# woeusb --version
@@WOEUSB_VERSION@@
root@hera:/home/rephlex# dpkg -l | grep woeusb
ii  woeusb                                        3.2.4-1~webupd8~cosmic0                           amd64        Bootable Windows installation/PE USB storage creator
root@hera:/home/rephlex# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Ubuntu Cosmic Cuttlefish (development branch)"
`

**Comment by Lin-Buo-Ren** [comment]
Should be fixed now, you may verify it by downloading the latest revision of the script, give it executable permission and rerun the command.

**Comment by Walms** [comment]
Thanks it's fixed for me. Thanks for all your work. This is a great tool!

**Comment by vdyshlevyi** [comment]
Still, have this problem on Linux Mint 19 Tara (I think it's because woe gui version 3.2.4 in repository).  But installation via shell using repository main page manual helped me. With version 3.2.9 everything is ok!

**Comment by thisaccountisforthisoneissue** [comment]
Thanks all of you, I wish every software problem I've ever had was solved this quickly

**Comment by thiennlinh** [comment]
Still, have this problem on Ubuntu 19.10:

Installation failed!
Exit code: 256
Log:
WoeUSB v3.3.1
==============================
Mounting source filesystem...
Wiping all existing partition table and filesystem signatures in /dev/sdc...
/dev/sdc: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
/dev/sdc: calling ioctl to re-read partition table: Success
Ensure that /dev/sdc is really wiped...
Creating new partition table on /dev/sdc...
Creating target partition...
Making system realize that partition table has changed...
Wait 3 seconds for block device nodes to populate...
Cluster size has been automatically set to 4096 bytes.
Creating NTFS volume structures.
mkntfs completed successfully. Have a nice day.
--2020-03-10 18:21:36--  https://github.com/pbatard/rufus/raw/master/res/uefi/uefi-ntfs.img
Resolving github.com (github.com)... pulse
52.74.223.119
Connecting to github.com (github.com)|52.74.223.119|:443... pulse
connected.
HTTP request sent, awaiting response... pulse
302 Found
Location: https://raw.githubusercontent.com/pbatard/rufus/master/res/uefi/uefi-ntfs.img [following]
--2020-03-10 18:21:37--  https://raw.githubusercontent.com/pbatard/rufus/master/res/uefi/uefi-ntfs.img
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.76.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.76.133|:443... pulse
connected.
HTTP request sent, awaiting response... pulse
200 OK
Length: 524288 (512K) [application/octet-stream]
Saving to: ‘/tmp/WoeUSB.u5CHtz.tempdir/uefi-ntfs.img’
     0K .........pulse
. .......... .......... .pulse
......... ..........  9%  382K 1s
    50K .......... ...pulse
....... .......... .......... .....pulse
..... 19%  761K 1s
   100K .......... .......... .......... .......... .......... 29%  892K 1s
   150K .........pulse
. .......... .......... .......... .......... 39%  998K 0s
   200K .......pulse
... .......... .......... .......... .......... 48%  932K 0s
   250K .....pulse
..... .......... .......... .......... .......... 58%  964K 0s
   300K ...pulse
....... .......... .......... .......... .......... 68%  993K 0s
   350K .pulse
......... .......... .......... ...pulse
....... .......... 78%  653K 0s
   400K .......... .......... .......... .pulse
......... .......... 87%  802K 0s
   450K .......... .......... .......... .......... .....pulse
..... 97%  997K 0s
   500K .......... ..                                         100% 23,8M=0,6s
2020-03-10 18:21:38 (790 KB/s) - ‘/tmp/WoeUSB.u5CHtz.tempdir/uefi-ntfs.img’ saved [524288/524288]
1024+0 records in
1024+0 records out
524288 bytes (524 kB, 512 KiB) copied, 0,186441 s, 2,8 MB/s
Mounting target filesystem...
Applying workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
Copying files from source media...
Installing GRUB bootloader for legacy PC booting support...
Installing for i386-pc platform.
grub-install: error: cannot find a GRUB drive for /dev/sdc1.  Check your device.map.
The command ""${command_grubinstall}" --target=i386-pc --boot-directory="${target_fs_mountpoint}" --force "${target_device}"" failed with exit status "1", program is prematurely aborted
Resetting workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
/usr/bin/woeusb: line 1683: echo: write error: Invalid argument
Warning!: command "echo 0 > /proc/sys/vm/dirty_background_bytes" - returned code  $?
/usr/bin/woeusb: line 1684: echo: write error: Invalid argument
Warning: command "echo 0 > /proc/sys/vm/dirty_bytes" - returned code  $?
Unmounting and removing "/media/woeusb_source_1583839275_13427"...
Unmounting and removing "/media/woeusb_target_1583839275_13427"...
You may now safely detach the target device
