### ISSUE TITLE
The future of WoeUSB

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [slacka/WoeUSB#209]
To @slacka, and anyone that are interested in the development of WoeUSB:

Currently, some of us have some considerations about the future of this project:

* I'd like to continue maintaining the Bash core of `woeusb`, but currently unable and somewhat unwilling to maintain the wxGTK graphical interface wrapper and the entire GNU build system madness.
* @WaxyMocha has re-implemented `woeusb` and a native graphical interface using Python and ~~PythonQt~~wxPython, it doesn't really fit into this repository though, and [I've asked them to move the effort](https://github.com/slacka/WoeUSB/pull/190#issuecomment-420934803) to [a new repository](https://github.com/WaxyMocha/WoeUSB-ng) for now.

As the current structure of the project isn't suitable now I would like to request to create a new "WoeUSB" GitHub organization and 3 new repositories:

* **WoeUSB/WoeUSB**: for the standalone bash script `woeusb`~~, moved from slacka/WoeUSB but removing all the bits that compose WoeUSB-wxgtk~~
* **WoeUSB/WoeUSB-frontend-wxgtk**: For the current wxGTK implementation of the wrapper application of `woeusb`, moved/cloned from slacka/WoeUSB, **it will be separated from the `woeusb` package and become an (already unmaintained), independent product**
* **WoeUSB/WoeUSB-ng**: For the Python re-implementation of `woeusb` and its graphical interface by @WaxyMocha, moved/cloned from WaxyMocha/WoeUSB-ng

Comments and suggestions are welcomed.

**Comment by WaxyMocha** [comment]
It would be unfair to all people that contributed to WoeUSB, to just drop their work, so I think it is good idea.

Also, wxPython not PythonQt.

**Comment by Lin-Buo-Ren** [comment]
> Also, wxPython not PythonQt.

Oops!  Fixed.

**Comment by Abtektas** [comment]
Bash core is stable and working well but I'm agreeing about the UI.

**Comment by Lin-Buo-Ren** [comment]
This is a friendly re-ping to @slacka (also, @Congelli501) of this issue.

**Comment by WaxyMocha** [comment]
I want to ask for help anyone who knows how to create a Python script installer (make the script installable). I do not know how to do it and now I do not have free time for this project, but I hope that after graduation I will be able to devote some attention to this it.

**Comment by Lin-Buo-Ren** [comment]
Apologies for breaking the promise on the clone of the repositories to the new organization, it is done by now at the following locations:

* <https://github.com/WoeUSB/WoeUSB> (created from scratch)
* <https://github.com/slacka/WoeUSB> -> <https://github.com/WoeUSB/WoeUSB-frontend-wxgtk>
* <https://github.com/WaxyMocha/WoeUSB-ng> -> <https://github.com/WoeUSB/WoeUSB-ng>

Please start using the new repositories from now, the deprecation/obsoletion from the current repositories are not yet planned.

**Comment by WaxyMocha** [comment]
I have one question about WoeUSB-ng, what filenames should files in /bin have? `woeusb` is used by bash version but `woeusb-ng` might confuse users that just installed program.

**Comment by WaxyMocha** [comment]
So I've pushed "first" release of WoeUSB-ng, I'm not sure what to do now though :stuck_out_tongue:.

**Comment by WaxyMocha** [comment]
But I'm starting to think that using `woeusb-ng` and `woeusbgui-ng` would make less mess

**Comment by WaxyMocha** [comment]
@Lin-Buo-Ren  Are you alive? :stuck_out_tongue:

**Comment by OMGdaDPS** [comment]
glad to see that youve found time my friend! I hope that school and work are treating you right!

**Comment by OMGdaDPS** [comment]
A few months later and I finally have the beginnings of a solid foundation of the Linux system (along with a HEFTY amount of books in possession now too). Eventually, I will be able to help contribute to this. Any pointers as to what language I should learn?

**Comment by WaxyMocha** [comment]
You are interested in general `The future of WoeUSB` or in helping my python port? If first one I would suggest learning some c++ and wxWidgets (as this is lagging part of this program), if second then python 3.x (newest). In case of woeusb-ng, main problem is with distribution, I tried pip but it won't fit requirements (I can't hook into uninstallation process, and I don't want to leave unnecessary files). I think we need to package program into .deb (and other for other distribution), and that did not looked like easy task.

**Comment by OMGdaDPS** [comment]
All around really, but if we can keep it afloat by porting it to Python, then that would make sense, since it seems Python is a fairly easy language (def no harm intended) to learn. The question is, how easy is it to port it?

**Comment by WaxyMocha** [comment]
Well... [Here is already ported version](https://github.com/WaxyMocha/WoeUSB-ng)

**Comment by OMGdaDPS** [comment]
Should we talk somewhere else? I get a lot of errors thrown when trying to run the setup. It may be because of my version of Python on this desktop I am on though, because I'm not in my workshop lol. I use Anaconda otherwise.

**Comment by WaxyMocha** [comment]
Do you have discord? :p Or open issue in my repository.

**Comment by OMGdaDPS** [comment]
haha yes. Are you in any of the linux discords?

**Comment by WaxyMocha** [comment]
Arch, Waxy#0848

**Comment by OMGdaDPS** [comment]
you just had to be one of them, didnt you? lol. OMW

**Comment by WaxyMocha** [comment]
😁

**Comment by ZVNexus** [comment]
What's the current status of this?

**Comment by WaxyMocha** [comment]
We need somebody who knows and is willing to package WoeUSB-ng into, well, .deb would be a good start

**Comment by ZVNexus** [comment]
> 
> 
> We need somebody who knows and is willing to package WoeUSB-ng into, well, .deb would be a good start

To confirm, the last update to it was in May?

**Comment by WaxyMocha** [comment]
Yes, 20 of may, [link](https://github.com/WoeUSB/WoeUSB-ng)

**Comment by Lin-Buo-Ren** [comment]
/ping @slacka , we would really like to hear from your opinion for this topic.

**Comment by WaxyMocha** [comment]
WoeUSB-ng is now available on AUR for Arch users
https://aur.archlinux.org/packages/woeusb-ng/

**Comment by Lin-Buo-Ren** [comment]
This is the final notice to the currently responsible admin @slacka:

As this issue isn't processed well during this two years this GitHub project will be **completely obsoleted** in favor of the @WoeUSB namespaced one starting at **2020/10/10 0:00 UTC+8** (click [here](https://www.timeanddate.com/worldclock/fixedtime.html?msg=WoeUSB+%40slacka-namespaced+project+obsoletion+deadline&iso=20201010T00&p1=%3A) to convert to your timezone)

Apologies for the poor communication.

**Comment by Lin-Buo-Ren** [comment]
The migration has been made, apologies that it takes so long, though :(
