### ISSUE TITLE
Error code 256

### ISSUE THREAD

**Issue by maguve** [slacka/WoeUSB#216]
stallation failed!
Exit code: 256
Log:
WoeUSB v@@WOEUSB_VERSION@@
==============================
Error: Target device is currently busy, unmount all mounted partitions in target device then try again
Target device is busy, please make sure you unmount all filesystems on target device or shutdown the computer before detaching it.

LinuxMint 18.3
Pendrive 4gb 
Image iso win7

![erroe](https://user-images.githubusercontent.com/43810425/46583124-affa1800-ca1f-11e8-88fe-3c6b4562e2c8.jpg)

**Comment by Lin-Buo-Ren** [comment]
This is not a bug but an error, refer: https://github.com/slacka/WoeUSB/wiki/F.A.Q.#why-does-woeusb-cant-find-my-external-usb-drive-after-i-use-the-eject-button-in-filemanager-etc-to-unmount-its-filesystems

**Comment by maguve** [comment]
Thanks.. done :feelsgood:

**Comment by peternsomerset** [comment]
Hi, I had the same problem as above, using Fedora 33.  So I unmounted the USB drive with "Gnome Disks".
WoeUSB then waits for 3 seconds but only ran for about 10 seconds and reported "success" but of course it did not install the Win10 files!
I had some problems with old USB stick but bought new ones with no improvement.
Is it me or is there a reason why I cannot create a bootable stick?
Thanks for your time
