### ISSUE TITLE
Unable to create WIN10 1809 USB, 4GB file limitaion, WIN10 1803 copies fine.

### ISSUE THREAD

**Issue by tr0n69** [slacka/WoeUSB#223]
Version 3.2.10-1 Manjaro

Unable to copy WIN10 1809 to USB due to 4GB file limitaion.
WIN10 1803 copies just fine.

Installation failed!
Exit code: 256
Log:
WoeUSB v@@WOEUSB_VERSION@@
==============================
Mounting source filesystem...
Error: File "/media/woeusb_source_1542342710_25807/sources/install.wim" in source image has exceed the FAT32 Filesystem 4GiB Single File Size Limitation and cannot be installed.  You must specify a different --target-filesystem.
Refer: https://github.com/slacka/WoeUSB/wiki/Limitations#fat32-filesystem-4gib-single-file-size-limitation for more info.
Unmounting and removing "/media/woeusb_source_1542342710_25807"...
You may now safely detach the target device

**Comment by Lin-Buo-Ren** [comment]
The error message clearly indicates you've encountered a technical limitation, not a bug.  Use `NTFS` as the `--target-filesystem` and it should be fine.

**Comment by ecoonradt** [comment]
This is a terrible response.  User experience matters.  Why not consider changing the default to NTFS?  Why not consider exposing target file system in the UI?  Discoverable software is good software and this falls short.

**Comment by blurrred** [comment]
Seriously. Kind of f**ing stupid considering Window 10's .iso is 5.1GB.

**Comment by GoranSoce** [comment]
> Seriously. Kind of f**ing stupid considering Window 10's .iso is 5.1GB.
> 
> Edit: Upon further searching, I just have to say you people are f**ing idiots with how you design your software. I am legitimately disgusted that you have a GUI but you are too incompetent to get it to have the basic functionality necessary to accomplish its main purpose: flashing windows to a USB drive. It's straight up impossible to use WoeUSB's GUI to burn Windows 10 to a USB drive because some retard(s) thought it was a good idea to create hassle for the user. I'm kidding, odds are these people just suck at what they do.
> 
> Seriously (again), it's lazy trash like this that gives free software a bad reputation.

I just wish I could get the time back I spent trying to get this to work.
Take #16, wish me luck. This is insane.
