### ISSUE TITLE
Windows 10 October 2018 Update fails to flash

### ISSUE THREAD

**Issue by famouswolfe** [slacka/WoeUSB#225]
Pretty much what the title says, WoeUSB won't flash the Windows 10 October 2018 iso as it's 4.1Gb but WoeUSB complains that the filesize exceeds 4.0Gb limit.

Steps to reproduce:
1. Download Windows 10 October 2018 Update iso file from Microsoft's website
2. Download latest version of WoeUSB from GitHub or clone it using your distro's method etc. I'm on Ubuntu and installed it that way.
3. Insert an SD card formatted to NTFS or Fat32 (neither made a difference), attempt to flash the Windows 10 October 2018 Update iso.
4. Get error message every time.

Output of error message:
Installation failed!
Exit code: 256
Log:
WoeUSB v@@WOEUSB_VERSION@@
==============================
Mounting source filesystem...
Error: File "/media/woeusb_source_1542576563_3382/sources/install.wim" in source image has exceed the FAT32 Filesystem 4GiB Single File Size Limitation and cannot be installed.  You must specify a different --target-filesystem.
Refer: https://github.com/slacka/WoeUSB/wiki/Limitations#fat32-filesystem-4gib-single-file-size-limitation for more info.
Unmounting and removing "/media/woeusb_source_1542576563_3382"...
You may now safely detach the target device

**Comment by Youboontoo** [comment]
I was able to reproduce this error on my Ubuntu 18.04 box with a 128GB NTFS Flash Drive.
https://ibin.co/4N4h9lYa5R3r.png

**Comment by albfan** [comment]
See #144 

Speccially https://github.com/slacka/WoeUSB/issues/144#issuecomment-439613160

I think this should aim for a check in GUI (use ntfs target-filesystem)

**Comment by Lin-Buo-Ren** [comment]
@albfan Thanks!

> I think this should aim for a check in GUI (use ntfs target-filesystem)

Unfortunately, no one is capable of tweaking the GUI code as of now.

**Comment by mhchau** [comment]
Seems the command line mode can be the way out,  the below works in my case:

woeusb --target-filesystem NTFS --device Win10_1809Oct_EnglishInternational_x64.iso /dev/sda

**Comment by neatcode** [comment]
@mhchau 's workaround worked for me. Must do from command line / terminal. Stuggled with this problem for awhile. Thanks mhchau!

**Comment by ZajferX** [comment]
> Seems the command line mode can be the way out, the below works in my case:
> 
> woeusb --target-filesystem NTFS --device Win10_1809Oct_EnglishInternational_x64.iso /dev/sda

this was the way for me to "woeusb --target-filesystem NTFS --device" seems to do the trick .. thank u

**Comment by Lin-Buo-Ren** [comment]
In the future, WoeUSB will _attempt_ to do the filesystem unmount automatically.

**Comment by RobertMVelasquez1996** [comment]
I also had the same problem. But the terminal command worked without a hitch for me. Just a small warning, you need to do it in sudo, otherwise, it will not work.

**Comment by ClaymorePT** [comment]
@mhchau your workaround also worked for me. Thank you!

**Comment by Torxed** [comment]
This should be documented in the [limitations](https://github.com/slacka/WoeUSB/wiki/Limitations#fat32-filesystem-4gib-single-file-size-limitation) section. Because this was annoying as f***.

Especially since every guide on the internet says "use this tool" and you can't get past this unless you dig deep and find one of these posts. The tool tell you to go to the above URL, at leat that URL can point towards this issue or just the command like to solve it. (the command line works fine)

**Comment by Lin-Buo-Ren** [comment]
I've added an example command to solve the issue, feel free to improve it.

**Comment by david114** [comment]
@mhchau 
Thanks man. Works as it should.

**Comment by AnhDungHedspi61** [comment]
@mhchau Thanks man.

**Comment by MatthewBooth** [comment]
![screenshot from 2019-02-12 13-27-15](https://user-images.githubusercontent.com/5381861/52638651-51134680-2eca-11e9-999c-156cf0eb287d.png)
![screenshot from 2019-02-12 13-27-40](https://user-images.githubusercontent.com/5381861/52638652-51134680-2eca-11e9-86d2-e353d7b7332c.png)

Had the same issue @mhchau's suggestion worked (or appears to be)

**Comment by r3d9u11** [comment]
> Seems the command line mode can be the way out, the below works in my case:
> 
> woeusb --target-filesystem NTFS --device Win10_1809Oct_EnglishInternational_x64.iso /dev/sda

Thanks!
Why WoeUSB can't do that automatically or doesn't allow to do it from GUI ?

**Comment by smileymalaise** [comment]
The problem persists on Ubuntu MATE 18.04 using the latest WoeUSB from the PPA.

The command line works flawlessly. This needs to be fixed.

**Comment by coverton341** [comment]
The command line work around worked for me as well. Thank you so much for that, I was in fits over this.

**Comment by coverton341** [comment]
The command line workaround worked for me as well. I am on Fedora 28 and the GUI method is defaulted to FAT32 without a way to change it. Thank you for this, I was in fits over it.
