### ISSUE TITLE
Explicitly use ntfs-3g

### ISSUE THREAD

**Issue by paulmenzel** [slacka/WoeUSB#239]
Using the latest version 3.2.12 from the master branch, `woeusb` aborted, because it couldn’t write to the target device. The problem is, that by default, `mount` uses the NTFS Linux kernel driver, only supporting read-only mode.

```
[263097.482279] sd 7:0:0:0: Attached scsi generic sg3 type 0
[263097.482432] sd 7:0:0:0: [sdc] 61282631 512-byte logical blocks: (31.4 GB/29.2 GiB)
[263097.482726] sd 7:0:0:0: [sdc] Write Protect is off
[263097.482727] sd 7:0:0:0: [sdc] Mode Sense: 53 00 00 08
[263097.482985] sd 7:0:0:0: [sdc] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[263097.510904]  sdc: sdc1
[263097.511986] sd 7:0:0:0: [sdc] Attached SCSI removable disk
[263458.802581]  sdc:
[263458.832936]  sdc: sdc1
[263463.929685] ntfs: driver 2.1.32 [Flags: R/O MODULE].
```

Manually specifying `-t ntfs-3g` in the script `woeusb` made it work.

```
$ git diff
diff --git a/src/woeusb b/src/woeusb
index 3284259..82c3de4 100755
--- a/src/woeusb
+++ b/src/woeusb
@@ -32,6 +32,8 @@ set \
        -o nounset \
        -o pipefail
 
+set -x
+
 ## Enable aliases for easy access to functions
 shopt -s expand_aliases
 
@@ -1362,6 +1364,7 @@ mount_target_filesystem(){
 
        mount \
                --options "${mount_options}" \
+               -t ntfs-3g \
                "${target_partition}" \
                "${target_fs_mountpoint}" \
                || (
```

This is incompatible with FAT of course.

**Comment by zilogat0r** [comment]
Hell,
how could you ADD -t ntfs-3g UNCONDITIONALLY? YOU BROKE FAT FUNCTIONALITY BY THIS LAME "FIX".

**Comment by Lin-Buo-Ren** [comment]
Thanks for the report, the patch is definitely incomplete and should be reverted.

**Comment by zilogat0r** [comment]
Merge: 7434985 bffb5c9
Author: slacka <lukebenes@yahoo.com>
Date:   Tue Nov 19 18:09:10 2019 -0500
zilog@sinclair/tmp/woeusb/WoeUSB/src $ git diff f78c1376da53ebf874a3b7703ae4478ab0854a20
diff --git a/src/woeusb b/src/woeusb
index 04725bd..8836885 100755
--- a/src/woeusb
+++ b/src/woeusb
@@ -26,6 +26,9 @@
 
 ## Makes debuggers' life easier - Unofficial Bash Strict Mode
 ## BASHDOC: Shell Builtin Commands - Modifying Shell Behavior - The Set Builtin
+
+PATH=$PATH:/usr/local/sbin
+
 set \
        -o errexit \
        -o errtrace \
@@ -1347,12 +1350,13 @@ mount_target_filesystem(){
                )
 
        # Determine proper mount options according to filesystem type
+       fstype_option=
        case "${target_fs_type}" in
                FS_FAT)
                        mount_options='utf8=1'
                ;;
                FS_NTFS)
-                       :
+                       fstype_option="-t ntfs-3g"
                ;;
                *)
                        printf_with_color \
@@ -1365,6 +1369,7 @@ mount_target_filesystem(){
 
        mount \
                --options "${mount_options}" \
+               ${fstype_option} \
                "${target_partition}" \
                "${target_fs_mountpoint}" \
                || (

**Comment by zilogat0r** [comment]
[diff.txt](https://github.com/slacka/WoeUSB/files/4110060/diff.txt)
this works for me OK for both FAT/NTFS and default on ClearLinux

**Comment by zilogat0r** [comment]
Fixed, tested by this.
[diff.txt](https://github.com/slacka/WoeUSB/files/4110090/diff.txt)

**Comment by Lin-Buo-Ren** [comment]
@JonnyTech Could you prepare a separate PR for the fix?

**Comment by JonnyTech** [comment]
@Lin-Buo-Ren see PR #296

There is no need to change anything in the GUI version because it simply calls `woeusb` with the following arguments:

```
woeusb --no-color --for-gui --target-filesystem FAT --device "path/image.iso" "/dev/sdX" 2>&1'
woeusb --no-color --for-gui --target-filesystem NTFS --device "path/image.iso" "/dev/sdX" 2>&1'
```

Then the script adds `-t vfat` or `-t ntfs-3g` as necessary.
