### ISSUE TITLE
Custom UEFI partition size

### ISSUE THREAD

**Issue by JonnyTech** [slacka/WoeUSB#249]
When using `woeusb` with the `--device` flag, an UEFI partition is created that is only 512kb. Is it possible to change the partition size? I want it to be bigger please.

**Comment by Lin-Buo-Ren** [comment]
This is currently hardcoded in the source:

* https://github.com/slacka/WoeUSB/blame/master/src/woeusb#L1093
* https://github.com/slacka/WoeUSB/blame/master/src/woeusb#L1149

You may change the size as this patch did: https://github.com/slacka/WoeUSB/commit/a3af891cc04db98d5acb668102bdf0d4714b64c7

**Comment by JonnyTech** [comment]
Thank you for identifying the relevant commit. I may learn a bit of Python and submit a PR :)
