### ISSUE TITLE
Several errors in both GUI and CLI

### ISSUE THREAD

**Issue by ieffedmybffjill** [slacka/WoeUSB#255]
* [X] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed

## Issue Reproduce Instructions
> sudo woeusb --target-filesystem NTFS --device 7601.24214.180801-1700.win7sp1_ldr_escrow_CLIENT_HOMEPREMIUM_x64FRE_en-us.iso /dev/sdc

## Expected Behavior
> well that's a silly question isn't it?

## Current Behavior
> in CLI:

Wiping all existing partition table and filesystem signatures in /dev/sdc...
wipefs: error: /dev/sdc: probing initialization failed: No medium found
The command "wipefs --all "${target_device}"" failed with exit status "1", program is prematurely aborted

Not sure what woeusb is inputting to wipefs to create that error, but manually performing it properly before running woeusb doesn't solve the problem. 

in GUI:
fails because it tries to write a 7GB iso to FAT32 and there's no option in the GUI to specify NTFS. this is extremely stupid.

### WoeUSB Version
> most recent from Ubuntu WebUpd8 PPA

### GNU Bash Version
> GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)

### Information about the Operating System
> Ubuntu 18.04.2 LTS

### Information about the Source Media
> Win 7 ISO from MSDN

### Information about the Target Device
> USB flash drive not that it matters

**Comment by JonnyTech** [comment]
> most recent from Ubuntu WebUpd8 PPA

Please try compiling the latest release from [GitHub releases](https://github.com/slacka/WoeUSB/releases)

> there's no option in the GUI to specify NTFS. this is extremely stupid.

This was fixed / added in #253

**Comment by ieffedmybffjill** [comment]
> > most recent from Ubuntu WebUpd8 PPA
> 
> Please try compiling the latest release from [GitHub releases](https://github.com/slacka/WoeUSB/releases)
> 
> > there's no option in the GUI to specify NTFS. this is extremely stupid.
> 
> This was fixed / added in #253

thanks this worked
