### ISSUE TITLE
grub-install: error: unknown filesystem

### ISSUE THREAD

**Issue by Leangeful** [slacka/WoeUSB#260]
## Issue Reproduce Instructions
>  Launch WoeUSB by running 
`sudo woeusb --target-filesystem NTFS --device ~/Downloads/Win10_1809Oct_v2_German_x64.iso /dev/sdb --verbose`

## Current Behavior
>Installing GRUB bootloader for legacy PC booting support...
i386-pc wird für Ihre Plattform installiert.
grub-install: Fehler: Unbekanntes Dateisystem.
The command ""${command_grubinstall}" --target=i386-pc --boot-directory="${target_fs_mountpoint}" --force "${target_device}"" failed with exit status "1", program is prematurely aborted
Resetting workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
Unmounting and removing "/media/woeusb_source_1556125073_13382"...
Unmounting and removing "/media/woeusb_target_1556125073_13382"...
You may now safely detach the target device>

### WoeUSB Version
> 3.3.0
### grub-install Version
> 2.02
### WoeUSB Source
> Built from source code (latest release)

### GNU Bash Version
> GNU bash, Version 5.0.3(1)-release (x86_64-pc-linux-gnu)

### Information about the Operating System
> OS : Arch Linux x86_64
Kernel: 5.0.9-arch1-1-ARCH

**Comment by JonnyTech** [comment]
What is the output of `lsblk` and `blkid` after the error occurs?

**Comment by Leangeful** [comment]
lsblk -f 
>sdb
├─sdb1          ntfs        Windows USB 
└─sdb2          vfat        UEFI_NTFS

In blkid the usb drive doesn't show up. Are there any flags I should use?

**Comment by JonnyTech** [comment]
Thanks, can you show the full output rather than just that of the USB drive (it may be that other drives, fixed or removable, may be having an impact). Maybe try with and without `sudo`.

**Comment by Leangeful** [comment]
NAME            MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
>sda               8:0    0 931,5G  0 disk
├─sda1            8:1    0   350M  0 part
├─sda2            8:2    0 760,3G  0 part
├─sda3            8:3    0   191M  0 part  /boot
└─sda4            8:4    0 170,7G  0 part
  └─main        254:0    0 170,7G  0 crypt
    ├─main-root 254:1    0    70G  0 lvm   /
    ├─main-swap 254:2    0     1G  0 lvm   [SWAP]
    └─main-home 254:3    0  99,7G  0 lvm   /home
sdb               8:16   1     8G  0 disk
├─sdb1            8:17   1     8G  0 part
└─sdb2            8:18   1   512K  0 part

And today it shows up with blkid as well:
>/dev/sda1: LABEL="System-reserviert" UUID="844C59B94C59A728" TYPE="ntfs" PARTUUID="454b9d22-01"
/dev/sda2: UUID="A8165C40165C1224" TYPE="ntfs" PARTUUID="454b9d22-02"
/dev/sda3: LABEL="boot" UUID="b3ca5217-35f8-4231-bd88-5491f7027056" TYPE="ext4" PARTUUID="454b9d22-03"
/dev/sda4: UUID="fc2b1db2-9c10-4f69-9a19-8a6b2996b6ad" TYPE="crypto_LUKS" PARTUUID="454b9d22-04"
/dev/sdb1: LABEL="Windows USB" UUID="6CF7C8DC51273CDE" TYPE="ntfs" PTTYPE="dos" PARTUUID="b5b1854e-01"
/dev/sdb2: SEC_TYPE="msdos" LABEL_FATBOOT="UEFI_NTFS" LABEL="UEFI_NTFS" UUID="211D-AC99" TYPE="vfat" PARTUUID="b5b1854e-02"
/dev/mapper/main: UUID="JnnXIs-wKLv-3ffR-2rq6-oEdq-zpxb-yCfU33" TYPE="LVM2_member"
/dev/mapper/main-root: LABEL="root" UUID="fe70fc52-e8b2-4018-9f9f-381e41592655" TYPE="ext4"
/dev/mapper/main-swap: LABEL="swap" UUID="e31928a8-30b6-41a3-81a1-b2747373d6ec" TYPE="swap"
/dev/mapper/main-home: LABEL="home" UUID="94e21d8c-5866-4d82-858d-54e5b73bbf1d" TYPE="ext4"

**Comment by JonnyTech** [comment]
All looks ok there. Hmm...

Because `grub-install` is failing then maybe it is finding a problem with the disk.

Please try `sudo wipefs /dev/sdb --all --force` followed by `sudo dd if=/dev/zero of=/dev/sdb bs=4M count=32`.

Then run `woeusb` with the `--verbose` flag again and report back what happens.

**Comment by Leangeful** [comment]
Exact same results.
I also tried to completely zero with `sudo dd status=progress if=/dev/zero of=/dev/sdb bs=1M`, still same result.

**Comment by JonnyTech** [comment]
OK, the disk does not report any error. Try this:

```
sudo wipefs /dev/sdb --all --force
sudo parted /dev/sdb mklabel msdos
sudo parted /dev/sdb mkpart primary ntfs 0% 100%
sudo mkfs.ntfs -f /dev/sdb1
mkdir /tmp/usb
sudo mount /dev/sdb1 /tmp/usb
sudo grub-install --target=i386-pc --boot-directory=/tmp/usb --force /dev/sdb
```
This essentially does what `woeusb` does.

My result after the last command (which will take a while on an NTFS system) is:

```
Installing for i386-pc platform.
Installation finished. No error reported.
```

If you still encounter a problem then there is a problem with your system setup.

**Comment by Leangeful** [comment]
Ah
>i386-pc wird für Ihre Plattform installiert.
grub-install: Fehler: Kanonischer Pfad von »/tmp/usb/grub/i386-pc« konnte nicht ermittelt werden.
(Failed to get canonical path of »/tmp/usb/grub/i386-pc«)

Ok, while it's apparently not a woeusb issue, any ideas?

**Comment by Lin-Buo-Ren** [comment]
Is you running WoeUSB in a live session?  There's is a known GRUB issue that the installation script will be confused by the copy on write filesystem.

**Comment by Leangeful** [comment]
Hm no it's not a live session. I'm using lvm instead of normal partitions though, that might be the problem?

**Comment by JonnyTech** [comment]
In your test can you replace:

```
sudo parted /dev/sdb mkpart primary ntfs 0% 100%
sudo mkfs.ntfs -f /dev/sdb1
```

with:

```
sudo parted /dev/sdb mkpart primary fat32 0% 100%
sudo mkfs.vfat -F 32 /dev/sdb1
```

And let us know if grub installs correctly on that FAT32 drive.

Also, your NTFS driver may be unsupported, what is the result of:

```
mkfs.ntfs --version
apt-cache policy ntfs-3g
```

Mine are:

```
mkntfs v2016.2.22AR.1 (libntfs-3g)
Installed: 1:2016.2.22AR.1+dfsg-1+deb9u1
```

Which Linux distro are you running?

**Comment by Leangeful** [comment]
No errors on fat32 ... 
>mkfs.ntfs --version
mkntfs v2017.3.23 (libntfs-3g)
pacman -Q ntfs-3g
ntfs-3g 2017.3.23-3 

Arch Linux (see bottom of first post)

**Comment by JonnyTech** [comment]
> Arch Linux (see bottom of first post)

Sorry, I missed that.

> pacman -Q ntfs-3g

Good catch, I should not assume Debian.

> ntfs-3g 2017.3.23-3

Are you able to try `ntfs-3g 2016.2.22`?

> Kernel: 5.0.9-arch1-1-ARCH

I am on `4.19.25`, an you try a `v4.x` kernel?

Thanks for your testing, patience and feedback so far. It would be great to get to the root of this. I shall try some updates on my system to replicate your issues.

**Comment by ben4ever** [comment]
I experienced the same issue:
```
Installing GRUB bootloader for legacy PC booting support...
Installing for i386-pc platform.
grub-install: error: failed to get canonical path of `/media/woeusb_target_1586806625_32237/grub/i386-pc'.
The command ""${command_grubinstall}" --target=i386-pc --boot-directory="${target_fs_mountpoint}" --force "${target_device}"" failed with exit status "1", program is prematurely aborted
```

In my case I noticed that the USB flash drive started to play up a lot when I did some further tests afterwards. Here some extracts from `dmesg`:
```
scsi 6:0:0:0: Direct-Access     Generic  Flash Disk       8.07 PQ: 0 ANSI: 4
sd 6:0:0:0: Attached scsi generic sg2 type 0
sd 6:0:0:0: [sdb] 15728640 512-byte logical blocks: (8.05 GB/7.50 GiB)
sd 6:0:0:0: [sdb] Write Protect is off
sd 6:0:0:0: [sdb] Mode Sense: 23 00 00 00
sd 6:0:0:0: [sdb] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
 sdb: sdb1 sdb2
sd 6:0:0:0: [sdb] Attached SCSI removable disk
sd 6:0:0:0: [sdb] Write Protect is on
sd 6:0:0:0: [sdb] Mode Sense: 23 00 80 00
 sdb: sdb1 sdb2
...
print_req_error: critical target error, dev sdb, sector 3743872
Buffer I/O error on dev sdb1, logical block 466960, lost async page write
sd 6:0:0:0: [sdb] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
sd 6:0:0:0: [sdb] tag#0 Sense Key : Data Protect [current]
sd 6:0:0:0: [sdb] tag#0 Add. Sense: Write protected
sd 6:0:0:0: [sdb] tag#0 CDB: Write(10) 2a 00 00 39 a0 80 00 00 f0 00
```

I later compiled `woeusb` from source to see if that version would work. At this stage I didn't notice those errors in `dmesg` yet (otherwise I would've tried another USB flash drive right away before compiling from source). But I eventually ran the compiled `woeusb` on a new USB flash drive and everything worked fine then:
```
Installing GRUB bootloader for legacy PC booting support...
Installing for i386-pc platform.
Installation finished. No error reported.
```

So it may just have been a faulty USB flash drive that was the cause. I don't think that compiling `woeusb` from source made any difference.
