### ISSUE TITLE
PPA Doesn't Contain Package

### ISSUE THREAD

**Issue by Thomashighbaugh** [slacka/WoeUSB#264]
## PPA 
The ppa for ubuntu offered did not have the package. Not sure if its me getting the name incorrect (though I tried the regex expressions too and still no luck) or the maintainer doesn't have it up *though I appreciate ap-hotspot he/she is maintaining*

Not to worry I built it using the dkpg approach, your program is vital to my side gig fixing Windows 10 computers without using that garbage on any of my machines. Thanks!

## Suggestion

Why give instructions to make the .deb file? It is just a few commands that you could do on your machine (including changing the version number) and offer it as the .deb file thus saving you annoying issues and the users frustration and time. While I don't mind doing it, I am a fringe case (especially for a developer, I don't even use Mac!) but a lot of your issues would never be raised to just build the package. __Just a thought__

**Comment by OMGdaDPS** [comment]
Same here, and its been like that for a bit now. I am also new to linux, so i dont even know how to build the package yet...

**Comment by Thomashighbaugh** [comment]
Late response __sorry__ 
---
__Here is the directions to install my .deb file:__
 Note: this works across my systems, so I imagine it will work for yours or anyone else who is looking for the .deb file  

# Deb File 
> This assumes you are using a Debian or Ubuntu based OS
## All GUI method 
- Navigate to [this](https://github.com/Thomashighbaugh/WoeUSB/blob/master/woeusb_3.3.0-1-g463f6fa_amd64.deb) link 
- Hit the download button 
- Open the folder containing the downloaded .deb file 
- Right click and select open with 
- Select the application you use for install deb files 
   - Gnome has this functionality via its "Software Center" but other applications such as GDebi are available
- Click install and enter your password
### AND BAM! WoeUSB is installed 
---
## Command Line Interface Instructions
> Using BASH shell on a Ubuntu or Debian OS 
> Dependencies: git  
```BASH
sudo apt-get update 

sudo apt-get upgrade -y 

sudo apt-get install git

git clone https://github.com/Thomashighbaugh/WoeUSB

cd WoeUSB 

sudo dpkg -i woeusb_3.3.0-1-g463f6fa_amd64.deb

cd ..

sudo rm -r WoeUSB
```

### AND BAM! WoeUSB is installed
#### (and the extra files are removed from your starting directory) 
---

**Comment by Thomashighbaugh** [comment]
__Also!__

In case you want to make your own .deb file in case your architecture is different or you don't trust random people... I won't be offended, here is the selection of the README.md file on exactly that (with some extra commands for getting the dependencies so you don't get lost and clean up at the end)!

---

## Build & Install WoeUSB
```shell
# For Debian and Ubuntu based distributions
sudo apt-get update 

sudo apt-get upgrade -y 

$ sudo apt-get install gdebi git 

$ git clone https://github.com/slacka/WoeUSB

$ cd WoeUSB  

$ dpkg-buildpackage -uc -b # NOTE: Currently, due to a bug in the build system, this command will fail if the source's path contains space or single quotes, refer to issue #84 for details

# to install using the debian package manager 
dpkg -i woeusb_<version>_<architecture>.deb

# to install using gdebi
$ sudo gdebi ../woeusb_<version>_<architecture>.deb

# to remove the extra files in the working directory (though you might want to save the .deb file)

$ cd ..

$ rm -r WoeUSB

**Comment by OMGdaDPS** [comment]
thank you!

**Comment by carlcorder** [comment]
Same issue here. It looks like the webupd8 ppa no longer contains `woeusb` (as you stated).

```bash
sudo add-apt-repository ppa:nilarimogard/webupd8
 The main Web Upd8 PPA maintained by: http://www.webupd8.org/

To add this PPA, simply paste this in a terminal:
sudo add-apt-repository ppa:nilarimogard/webupd8

Packages in this PPA: audacious, ap-hotspot, awn-applet-radio, awn-applet-wm, calise, cmus, 
dockbarx, dockbarx-themes-extra, dropbox-share, emerald, exaile, fbmessenger, gnome-subtitles, 
gnome-window-applets, grsync, grive, gthumb, launchpad-getkeys, mc, mdm (Mint Display Manager),
 minitunes, minitube, musique, notifyosdconfig, nautilus-columns, powertop, ppa-purge, 
rosa-media-player, fixed pulseaudio-equalizer, subtitleeditor, syncwall, umplayer,
 unity-reboot, wimlib, youtube-dl, xfce4-dockbarx-plugin, xournal, yad, yarock and others.
 Almost all packages are updated to their latest version.
```

Perhaps even more confusing, when I launch Ubuntu Software (I'm using 19.04) I can find the woe-usb package:

![ubuntu software](https://i.ibb.co/QYyqS8Z/woeusb-ubuntu-software.png)

However, after installing, it never launches.

**Comment by Thomashighbaugh** [comment]
That is truly weird! Seems like Gnome software is likely operating on black magic conjured from people muttering "free as in freedom" after all.

**Comment by OMGdaDPS** [comment]
Just wanted to say thanks again man. It works great!

**Comment by Thomashighbaugh** [comment]
Not using the thing on systems with PPA repos, it is on AUR so my issues with it not being on a PPA don't really matter anymore but I hope they fixed it!
