### ISSUE TITLE
Error 256 When Installing Windows 10 to USB

### ISSUE THREAD

**Issue by iwanio** [slacka/WoeUSB#266]
I am trying to load a Windows 10 installer 10 USB on my Ubuntu 18.04 system. I keep trying to install it but it always comes up with Error 256. It says to unmount my drive but when I do, WoeUSB can't detect it. I have also tried formatting the drive with NTFS prior to using WoeUSB but I get the same error. Can anyone figure out why this won't work?

**Comment by ski007** [comment]
maybe ....
https://github.com/slacka/WoeUSB/issues/263

**Comment by ski007** [comment]
try the terminal with this command:
`sudo woeusb --device /path_to_file/windows.iso /dev/sdb --tgt-fs NTFS --verbose`

**Comment by ski007** [comment]
or
```
sudo apt-get install python3-pip
sudo pip3 install py-winusb
sudo pywinusb
```
https://github.com/Mati365/pyWinUSB

**Comment by calegria** [comment]
I confirm this issue on ArchLinux. The ISO is correctly created since I was able to install Windows10, but WoeUSB does not finish correctly. The mounted devices for both the USB and the *iso image need to be unmounted manually.
