### ISSUE TITLE
Fails on "Resetting workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files"

### ISSUE THREAD

**Issue by mrvik** [slacka/WoeUSB#267]
## Good Habit Checklist for Issue Reporting

* [X] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed
* [X] I've built the latest development snapshot using the instructions in README and verified that the issue can still be reproduced (for bug reports)

## Issue Reproduce Instructions
> 1. Launch WoeUSB by running `sudo woeusb -l MIERDOWS_7 -d Win7_Pro-SP1_N.iso /dev/sdg`
> 2. Wait

## Expected Behavior
> No error

## Current Behavior
> WoeUSB errors with message:
```
Resetting workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
/usr/bin/woeusb: line 1676: echo: write error: Invalid argument
The command "exit 0" failed with exit status "1", program is prematurely aborted
```
### WoeUSB Version
> From `pacman -Q woeusb`: 3.3.0-1 (the last 1 comes from the Arch packaging system)

### WoeUSB Source
> Built from source code using AUR package [woeusb](https://aur.archlinux.org/packages/woeusb/)

### GNU Bash Version
> `GNU bash, version 5.0.7(1)-release (x86_64-pc-linux-gnu)`

### Information about the Operating System
> `Description:	Arch Linux`

### Information about the Source Media
> "Windows 7 Pro N SP1 from Microsoft"

### Information about the Target Device
>  SanDisk Cruzer Slice 8GB USB2.0

**Comment by Lin-Buo-Ren** [comment]
The related implementation: https://github.com/slacka/WoeUSB/blob/master/src/woeusb , you may want to comment out the `workaround_linux_make_writeback_buffering_not_suck` function call in the `init` function as a temporary workaround.

The error might be related to the changes of the Linux kernel, which version of the kernel you're using right now?

**Comment by mrvik** [comment]
> The error might be related to the changes of the Linux kernel, which version of the kernel you're using right now?

Currently I'm working with 5.1.12-arch1-1-ARCH

**Comment by Lin-Buo-Ren** [comment]
What is the result of running the `echo 0 > /proc/sys/vm/dirty_background_bytes` command in a root shell?

**Comment by mrvik** [comment]
>What is the result of running the echo 0 > /proc/sys/vm/dirty_background_bytes command in a root shell?

The same: `sh: line 0: echo: write error: Invalid argument`

**Comment by Rabjerg** [comment]
I have the same issue.

WoeUSB Version
`woeusb-git 3.3.0.r0.g5e9a3a7-1`

WoeUSB Source
`Built from source code using AUR package woeusb`

GNU Bash Version
`bash 5.0.007-1`

Information about the Operating System
`Arch Linux, 5.2.0-1-MANJARO`

Information about the Source Media
`"Windows 7 Pro SP1 from Microsoft"`

Information about the Target Device
`SanDisk SDCZ80-032G-GAM46 (32GB USB3)`

"cat /proc/sys/vm/dirty_background_bytes" 
`0`

Could be the Arch 5.1+ Kernel, and/or writing Win7 images.

**Comment by louisvd** [comment]
I have the same issue.
Linux Version:  ```Fedora 30```
Kernel Version:  ```5.1.12-300.fc30.x86_64```
Bash version:  ```5.0.7(1)-release (x86_64-redhat-linux-gnu)```
WoeUSB Version:  ```3.2.12```
WoeUSB Source:  ```installed from the Fedora repository```
Sample execution output attached:
[woeusb.debug.log.gz](https://github.com/slacka/WoeUSB/files/3327772/woeusb.debug.log.gz)

Testing /proc:  
```
[root@fedora ~]# cat /proc/sys/vm/dirty_background_bytes
16777216
[root@fedora ~]# echo 0 > /proc/sys/vm/dirty_background_bytes
-bash: echo: write error: Invalid argument```

**Comment by johndoe71rus** [comment]
Confirm
lubuntu 18.04 i686
kernel 5.1.15 (kernel.ubuntu.com/~kernel-ppa/mainline)
WoeUSB Version 3.3.0-1~webupd8~bionic0

cat /proc/sys/vm/dirty_background_bytes
0

**Comment by setzer22** [comment]
I also have the same issue as reported by other users. I have more or less the same setup as @louisvd 
I'm just commenting to clarify on the proposed workaround by @Lin-Buo-Ren. Basically, you need to comment lines: 311-312
```
workaround_linux_make_writeback_buffering_not_suck \
apply
```

and 1341-1342
```
workaround_linux_make_writeback_buffering_not_suck \
apply
```

**Comment by johndoe71rus** [comment]
so this is not a critical issue. can i ignore the error at the end of the procedure?

**Comment by fgordon** [comment]
I have the same issue.

Linux Version: ARCH
Kernel: 5.1.15-arch1-1-ARCH
woeusb-Version: 3.3.0

**Comment by sixtyfive** [comment]
`The command "exit 0" failed with exit status "1".`

Basically the funniest error message ever.

**Comment by mrvik** [comment]
@johndoe71rus
>so this is not a critical issue. can i ignore the error at the end of the procedure?

Yes, you can ignore it as the device is created and able to boot. The step is not needed for the boot device but to restore the common behavior of the cache. Anyway all remains stable.

**Comment by johndoe71rus** [comment]
One wish. Put error message like this in a scrolling textbox. The full window does not fit even on a screen height of 1024, I think at a height of 1080 as well.

**Comment by rdlmda** [comment]
Same issue on Fedora 30 (5.1.16-300.fc30.x86_64)

**Comment by Pitrr** [comment]
Same issue on arch (5.2.1-arch1-1-ARCH)

**Comment by ckrzen** [comment]
> Same issue on Fedora 30 (5.1.16-300.fc30.x86_64)

and 

  Operating System: Fedora 30 (Workstation Edition)
       CPE OS Name: cpe:/o:fedoraproject:fedora:30
            Kernel: Linux 5.2.5-200.fc30.x86_64

**Comment by edricus** [comment]
same 5.2.8-arch1-1-ARCH nothing on linux works for creating a bootable windows usb please fix...

**Comment by mrvik** [comment]
It works, but the final step to reset the workaround fails. Simply umount the device after the error and boot the USB

**Comment by jamespharvey20** [comment]
Commits were pushed on Aug 3, and the github PKGBUILD was modified to include the patch, but the PKGBUILD was never pushed to the AUR.  The PKGBUILD also really needs to change pkgrel from 1 to 2, for anyone who already has it installed.

**Comment by tdschmidl** [comment]
Anyone else wondering how to apply the needed patch.
Use the file "fix.patch": https://github.com/zer0def/PKGBUILDs/commit/6ffe6d7b13c9ca50e08b88603f07a56c677a0bf5
and apply to the checked out sources (I needed to specify src/woeusb when using patch < fix.patch)
Afterwards compile WoeUSB on your machine using: https://github.com/slacka/WoeUSB/blob/master/README.md

**Comment by bjornfor** [comment]
Ping. (Another distro worked around this [here](https://github.com/NixOS/nixpkgs/pull/70826) (based on the patch above), but I'd really prefer upstream problems to be handled upstream...)

**Comment by gudge25** [comment]
still have the same issue 
woeusb is already the newest version (3.3.0-1~webupd8~bionic0).

**Comment by brockness** [comment]
Pop OS 19 here. Same issue.

**Comment by RickardBremer** [comment]
Linux nuc 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

/usr/bin/woeusb: line 1676: echo: write error: Invalid argument
The command "exit 0" failed with exit status "1", program is prematurely aborted

**Comment by Cytomax55** [comment]
/usr/bin/woeusb: line 1676: echo: write error: Invalid argument
The command "exit 0" failed with exit status "1", program is prematurely aborted

Running Kubuntu 18.04.3
5.0.0-36-generic #39~18.04.1-Ubuntu
Burning Win10_1909_English_x64.iso 64 bit to a usb drive formatted in NTFS

HOWEVER the USB installed Windows 10 without issues

BTW please fix the error pop up.. i cant scroll down and read the entire error, it took me forever to figure out i could ctrl+a and copy the error log and paste it into a document to read it.
This error most likely happens a lot more and people cant read the whole error so they cant report it

**Comment by tim-win** [comment]
Still a problem.

**Comment by geole** [comment]
It is necessary to modify the script on 18.04.3
 cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic

 ' ATTENTION Action non FAITE Resetting workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.'
##           echo 0 > /proc/sys/vm/dirty_background_bytes
##           echo 0 > /proc/sys/vm/dirty_bytes
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

**Comment by greenx** [comment]
IMHO, you can’t do that.
These options have paired options.
**_dirty_bytes vs. dirty_ratio
dirty_background_bytes vs. dirty_background_ratio_**
With them, you indicate the size of the cache, either in bytes or as a percentage.
The kernel automatically sets the other option to 0.
You can’t just turn the cache off and on. A minimum of 2 pages (8192 bytes) should be.
Perhaps it would be more correct to simply flush all caches.
``` shell
echo 3 > /proc/sys/vm/drop_caches
```
https://www.kernel.org/doc/Documentation/sysctl/vm.txt

**Comment by oopscentral** [comment]
This kernel behaviour changed in linux >= 5.2 and the change was backported to 4.19, 4.14, 4.9 and 4.4 but not 3.16.

The change is [here](https://github.com/torvalds/linux/commit/e260ad01f0aa9e96b5386d5cd7184afd949dc457). Basically setting dirty_background_bytes or dirty_bytes to 0 doesn't do anything and never did. The kernel just silently ignored it rather than responding with an error code.

**Comment by iccaka** [comment]
I have the same issue. Mint 19.2 MATE, Kernel: 4.15.0-76-generic. When I unmount the usb and then put it in the computer where I want the image(in this case it's windows 10, don't ask why :D) installed, it works without any errors. Cheers ;)

**Comment by Lin-Buo-Ren** [comment]
Apologies for the ignorance.

@oopscentral

Thanks for your info, however at the time the _workaround_ is introduced it definitely worked, either as a root cause fix or as a side effect.

Reference: [cp - Why is my PC freezing while I'm copying a file to a pendrive? - Unix & Linux Stack Exchange](https://unix.stackexchange.com/questions/107703/why-is-my-pc-freezing-while-im-copying-a-file-to-a-pendrive)

**Comment by Lin-Buo-Ren** [comment]
This workaround is dropped in the new WoeUSB 5.0.0 release, we would like to thank everyone who contribute to the issue and apologies for the slow responding to it.
