### ISSUE TITLE
can I install windows in the same disk

### ISSUE THREAD

**Issue by flylzj** [slacka/WoeUSB#273]
hey guys!
I am looking for a method which can let me install windows without a usb device.
And someone recommend woeusb to me. But I am not sure can I install windows in the disk that my linux in.
This is my situation below（what i am holding）：

- a laptop installing archlinux

- an android mobile 

Hope you can help me,thank you!

**Comment by Lin-Buo-Ren** [comment]
WoeUSB requires a USB mass storage device to function, so unless you can make your android mobile emulate one there's little hope making that possible.
