### ISSUE TITLE
MainPanel.cpp line 163 can't read usb list

### ISSUE THREAD

**Issue by l4jos** [slacka/WoeUSB#284]
Error : Error from 'MainPanel.cpp' at line 163
Description: Can't read usb list !
/dev/sdb

Same issue when using sudo or calling woeusbgui as su root.
Last time I made this work by not using this fork, just the original one mentioned in description.

**Comment by JonnyTech** [comment]
You need to make both the `listUsb` and `listDvdDrive` files executable:

`chmod +x src/data/listUsb src/data/listDvdDrive`

**Comment by luckyboy94120** [comment]
that didn't work for me
