### ISSUE TITLE
Change package name (Debian)

### ISSUE THREAD

**Issue by locknet11** [slacka/WoeUSB#295]
While building dependencies for install woeusb it gives a missing dependencies error : 
 libwxgtk2.8-dev  &  libwxgtk3.0-dev

Because the name of these packages has been updated, it's necessary to modify "control" file in "debian" folder.

Rename : libwxgtk3.0-dev ------>  libwxgtk3.0-gtk3-dev

And now will generate correctly the .deb file.

**Comment by nilsjha** [comment]
Can confirm this issue on Debian Buster, it builded as usual after adding `| libwxgtk3.0-gtk3-dev,` as stated above.
