### ISSUE TITLE
New release potentiallllly?

### ISSUE THREAD

**Issue by ZVNexus** [slacka/WoeUSB#306]
Could we get a new release? Errors at end of creation, was fixed in November but we haven't had a new release since April of last year.
https://github.com/slacka/WoeUSB/commit/988b6f53bf7e5e8157b85d1f8e08a38ad3bff224

**Comment by Lin-Buo-Ren** [comment]
That seems to be a persuasive reason for a new release, I'll look into it.

**Comment by Lin-Buo-Ren** [comment]
[WoeUSB 3.3.1](https://github.com/slacka/WoeUSB/releases/tag/v3.3.1) has now being released.
