### ISSUE TITLE
Please update snap to 3.3.1

### ISSUE THREAD

**Issue by kerozoli** [slacka/WoeUSB#308]
Could you please update the snap version to 3.3.1?
(Not sure if it's supported by you)

**Comment by Lin-Buo-Ren** [comment]
Hello, this snap is not maintained by us, the publisher is (as shown in [the snap's store page](https://snapcraft.io/woe-usb)) Ermesto Castellotti (ernytech), which appears to be hosting the snap's building recipe at [ErnyTech/woeusb.snap: Snap package for WoeUSB](https://github.com/ErnyTech/woeusb.snap).  I would suggest filing an issue at [their issue tracker](https://github.com/ErnyTech/woeusb.snap/issues).

**Comment by Lin-Buo-Ren** [comment]
Note that we do plan to release an official snap in the near future<sup>TM</sup>, I would suggest check back periodically for one.
