### ISSUE TITLE
seriously add option --no-grub or something !!!

### ISSUE THREAD

**Issue by AkgunFatih** [slacka/WoeUSB#309]
okey i give WoeUSB a second change
the thing is why is grub needed for a windows installation usb anyway ?
with this grub install i takes a damn long time to finnish
so for people with uefi like me cant you add an option to exclude grub-install thing ?

**Comment by Alexander88207** [comment]
To boot into UEFI mode a seperate boot partition (efi loader) is needed and the windows images are without the efi loader. So grub does the job

**Comment by AkgunFatih** [comment]
> To boot into UEFI mode a seperate boot partition (efi loader) is needed and the windows images are without the efi loader. So grub does the job. (Correct me if i am wrong.)

Windows Iso already has efi folder inside iso file

**Comment by Lin-Buo-Ren** [comment]
The reason behind WoeUSB using GRUB is that:

* In the legacy PC boot scheme, a VBR bootloader is required for chainloading the Windows bootloader, which as far as I concerned does not have an existing free implementation(the one in ms-sys is not free and thus can't be included in WoeUSB)
* In the UEFI boot scheme, it is rather technically possible to extract and reuse Windows's EFI bootloader, just that someone has to make a patch for it

**Comment by AkgunFatih** [comment]
never use woeusb again
its wasting time.
