### ISSUE TITLE
Error: Source media is currently mounted

### ISSUE THREAD

**Issue by jjangga0214** [slacka/WoeUSB#312]
## Good Habit Checklist for Issue Reporting

* [x] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed
* [ ] I've built the latest development snapshot using the instructions in README and verified that the issue can still be reproduced (for bug reports)

## Issue Reproduce Instructions

1. Open GUI
2. Select a `.iso` image by `Source: From a disk image (iso)`: 
3. Select a target device.
4. Click `install` button.

## Expected Behavior

No error

## Current Behavior

WoeUSB errors with the message below.

![Screenshot from 2020-03-22 15-35-33](https://user-images.githubusercontent.com/28584151/77244088-c8caad80-6c54-11ea-9710-763149fdb410.png)

```
Installation failed!
Exit code: 256
Log:
WoeUSB v@@WOEUSB_VERSION@@
==============================
Error: Source media is currently mounted, unmount the partition then try again
You may now safely detach the target device
```

### WoeUSB Version

The lastest version published on PPA.

### WoeUSB Source

Installed from WebUpd8 PPA

### GNU Bash Version

It's 5.0.3, but I used GUI.

### Information about the Operating System

Ubuntu 19.04

### Information about the Source Media

Windows 10 official iso file from the official website 

### Information about the Target Device

SanDisk 15G

**Comment by jjangga0214** [comment]
It turned out the image was compromised.
However, the error message is still not related to the source image's validity.
Because of another possibility of the cause of this happening, I'm not closing this issue.

**Comment by SirClarks** [comment]
Just curious, is the target device actually unmounted. Did you check "Disks" utility and pressed the little "block/square" icon below the partition for unmount?

**Comment by jjangga0214** [comment]
@SirClarks To my memory, yes, I recall I checked it was unmounted by "Disks" utility.

**Comment by goranmiric** [comment]
Had the same issue: Error: `Source media is currently mounted...`
The .iso file was on another disk, not the same as the system is and I needed to copy .iso to /home directory and after that it worked.
