### ISSUE TITLE
How can I use this?

### ISSUE THREAD

**Issue by SharkMachine** [slacka/WoeUSB#313]
If I have my USB stick mounted, it complains that it is mounted.
If it isn't mounted, my USB stick is not listed.
How am I supposed to use this tool?

**Comment by Lin-Buo-Ren** [comment]
Check out [Why does WoeUSB can't find my external usb drive after I use the "eject" button in FileManager etc. to unmount its filesystems?·Preparing Bootable Microsoft Windows(R) Media·F.A.Q. · slacka/WoeUSB Wiki](https://github.com/slacka/WoeUSB/wiki/F.A.Q.#why-does-woeusb-cant-find-my-external-usb-drive-after-i-use-the-eject-button-in-filemanager-etc-to-unmount-its-filesystems) for more info.
