### ISSUE TITLE
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2

### ISSUE THREAD

**Issue by victor713** [slacka/WoeUSB#315]
## Issue Reproduce Instructions
> 1. Launch the build of WoeUSB by running `dpkg-buildpackage -uc -b`

## Expected Behavior
> No error

## Current Behavior
> WoeUSB errors with message "dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2"

### WoeUSB Version
> v3.3.1

### WoeUSB Source
> Built from source code, commit f21bb19e6aa575682b84c4e909e6509b04aa58e2
> Installed from Debian 9
> Installed from cloning the repository

### GNU Bash Version
> GNU bash, versión 4.4.12(1)-release (x86_64-pc-linux-gnu)

### Information about the Operating System
> Debian GNU/Linux 9.12 (stretch)

### Information about the Source Media
> "Debian 9" downloaded from <www.debian.org>

### Information about the Target Device
> TOSHIBA-TR200 (scsi) 256 Gb (SATA)

**Comment by osamuaoki** [comment]
I can't reproduce this bug.  I see another minor issue  for build which I will report.  But this old bug should be closed.  I am on Debian 10 (current stable release) and relatively good at Debian since I am Debian Developer.
