### ISSUE TITLE
version 'unknown' is invalid

### ISSUE THREAD

**Issue by Washiii** [slacka/WoeUSB#316]
When i run the command "mk-build-deps" this error appear:
![image](https://user-images.githubusercontent.com/52114739/77969518-3ebbbe00-72c0-11ea-94f3-9df4e3d58b8c.png)

**Comment by brunoqs** [comment]
Use this command first ./setup-development-environment.bash then use mk-build-deps

**Comment by ciampix** [comment]
Please close this issue as it was already answered...
