### ISSUE TITLE
Support NTFS(...again!)

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [slacka/WoeUSB#32]
It's technically possible to use NTFS filesystem as the filesystem to store Windows installer files by utilizing the [UEFI NTFS bootloader](https://github.com/pbatard/uefi-ntfs) developed by the Rufus's author.

This has some advantages, like:
- No 4GiB single-file-size limitation
- Unified UTF-16 filename encoding, contrary to FAT's using whatever encoding the user's default codepage uses.
- Journal to prevent filesystem corruption

Of course, some dis-advantages, like:
- Will make certain flash drives' memory controller's FAT structure-only optimization fail, leading to possible low data transfer efficiency.

**Comment by slacka** [comment]
Unless this projects plans to broaden its support to include more than Windows images, I think this is an unnecessary feature. It would be an interesting technical accomplishment, but I don't see any benefit to the end user.

**Comment by Lin-Buo-Ren** [comment]
We now have flash drives up 64 and even 128GiB and WinUSB supports non-destructive `--install` mode, end user may want their flash drives having bootable Windows images while still storing their personal files, which may be easily bigger then 4GiB (4~8GiB for a DVD-rip video and 25GiB for a BD-rip).  I still consider this feature useful and (while not been able to by now) easily to be implemented.

**Comment by Lin-Buo-Ren** [comment]
NTFS filesystem support has now been added to WoeUSB 3.0.0, it's slow as heck comparing to FAT for some reason but it's usable.
