### ISSUE TITLE
Invalid partition table!

### ISSUE THREAD

**Issue by palikacska** [slacka/WoeUSB#320]
I've just created my first Windows 10 boot USB from an ISO with WoeUSB and the other computer I'm trying to install it halts with the following error after selecting the USB stick too boot from.

`Invalid partition table!`

However, the partition table seems to be valid.

```
Disk /dev/sdb: 29.3 GiB, 31466323968 bytes, 61457664 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xee447929

Device     Boot Start      End  Sectors  Size Id Type
/dev/sdb1        8192 61457663 61449472 29.3G  c W95 FAT32 (LBA)
```

Seems to be but **is not** because there is **no bootable flag** on **/dev/sdb1**. So I had to set the bootable flag manually, then I could boot Windows 10 installer from it.

I just can't believe there is nobody to make a bootable USB creator for Linux that could get even near to Rufus on Windows regarding simplicity and reliability. Wouldn't it be the most basic - and also the most important - thing to make a **bootable** USB drive partition bootable?

**Comment by ahmedessamdev** [comment]
I faced the same error! Setting the boot flag using Gparted fixed it.
Thanks @palikacska !
Please fix this issue in future releases

**Comment by Ezibenroc** [comment]
I got the same error and fixed it thanks to your tip, thanks.
