### ISSUE TITLE
More informative error message when iso is broken

### ISSUE THREAD

**Issue by ghost** [slacka/WoeUSB#322]
All usbs give the same error message, be it in the gui or command line. Not very informative.

Copying files from source media...
cp: error reading './boot/en-us/bootsect.exe.mui': Input/output error
The command "cp "${source_file}" "${dest_file}"" failed with exit status "1", program is prematurely aborted
/usr/bin/woeusb: line 1789: local: only_for_gui: readonly variable
The command "cp "${source_file}" "${dest_file}"" failed with exit status "1", program is prematurely aborted

Update: the problem was the iso file, which was broken (incomplete). Don't know if the issue is valid nonetheless because of the error message thing. I don't know if it could be more informative in this case.

**Comment by Lin-Buo-Ren** [comment]
It seems that your source media is corrupted, please check the data
consistency of your source image.

davidmoseler <notifications@github.com> 於 2020年5月19日 週二 上午8:57 寫道：

**Comment by davidmoseler** [comment]
Hi, indeed it was corrupted. The issue is that I took a lot of time to identify this. Maybe WoeUSB could detect source corruption and print a more informative message?
