### ISSUE TITLE
exFAT file system support

### ISSUE THREAD

**Issue by Ricky-Tigg** [slacka/WoeUSB#325]
Component installed from official site as _rpm_.
```
$ woeusb -V
3.3.1
$ lsb_release -d
Description:	Fedora release 32 (Thirty Two)
$ bash --version | head -1
GNU bash, version 5.0.17(1)-release (x86_64-redhat-linux-gnu)
```

## New feature request
Support of _Extended File Allocation Table_ (_exFAT_) file system

Hey, as you already guessed, the problem i encountered is related to one of the two options supported – **FAT32** .which is nevertheless displayed in the graphical interface as  _FAT_.

![image](https://user-images.githubusercontent.com/26058215/84375910-e7ec3200-abe8-11ea-9f6f-2da7b38c370e.png)

Selecting the other supported option, _NTFS_, allowed as expected the write operation. Though that option is not the best on non- Microsoft Windows OSs.

- Despite exFAT doesn’t match FAT32’s compatibility, it is more widely-compatible than NTFS. Mac OS X which includes only read-only support for NTFS, offers full read-write support for exFAT. exFAT drives can easily be accessed on Linux by installing the appropriate software. 

Use-case
- NTFS is appropriate for internal drives, while exFAT is appropriate for flash drives. Formatting an external drive with FAT32 may only be needed if exFAT isn’t supported on a device you need to use it with.
- When the size of a file to be written exceeds four GiB. There is no realistic file-size or partition-size limit.

**Comment by JonnyTech** [comment]
AFAIK there is no support at all for bootable exfat filesystems
