### ISSUE TITLE
Suggested fix for grammar errors in About sidebar

### ISSUE THREAD

**Issue by oceandays** [slacka/WoeUSB#333]
## Issue Reproduce Instructions
Sidebar of https://github.com/slacka/WoeUSB

## Current Behavior
Currently says:
"WoeUSB is a simple tool that enable you to create your own usb stick windows installer from an iso image or a real DVD. It is a fork of Congelli501's WinUSB."

## Expected Behavior
Rewrote it to:
"WoeUSB is a simple tool that enables you to create your own Windows installer USB stick from an ISO image or a physical DVD. WoeUSB is a fork of Congelli501's WinUSB."

## Diff between both versions
"WoeUSB is a simple tool that **enables** you to create your own **Windows installer USB stick** from an **ISO** image or a **physical** DVD. **WoeUSB** is a fork of Congelli501's WinUSB."

**Comment by Lin-Buo-Ren** [comment]
First of all, apologies for the ignorance.

Unfortunately, the only person who can edit the project description is @slacka , as the project is now migrated to <https://github.com/WoeUSB/WoeUSB> feel free to file an issue if you believe that its project description can be improved, thank you.
