### ISSUE TITLE
Debian/Ubuntu build instruction has rooms to improve

### ISSUE THREAD

**Issue by osamuaoki** [slacka/WoeUSB#337]
## Reproduce Instructions
I manually installed devscripts and every thing in Build-Depends (I think "git-core" is renamed to "git" by now but I see no reason to list it.) I used libwxgtk3.0-gtk3-dev

Then following README.md, 

```
$ dpkg-buildpackage -uc -b 
dpkg-buildpackage: warning:     debian/changelog(l1): version '@@WOEUSB_VERSION@@' is invalid: version number does not start with digit
LINE: woeusb (@@WOEUSB_VERSION@@) unstable; urgency=low
dpkg-buildpackage: info: source package woeusb
dpkg-buildpackage: info: source version unknown
dpkg-buildpackage: error: version number does not start with digit
```

Since we need real version, I needed to do:

`$ sed -ie 's/@@WOEUSB_VERSION@@/3.3.1/g' debian/changelog configure.ac src/woeusb*
`
on this git archive before building.  Then I got a nice Debian package!

I am not sure how exactly upstream is building this source.  There may be cleaner path.  (Some how, "make dist" failed so I didn't check tarball based build.)

I see there are some Ubuntu package at http://www.webupd8.org/ but no Debian package (I see debian.org address in git commit).  Does any one packaging this for Debian?  (I am DD)

**Comment by osamuaoki** [comment]
OOps, ./setup-development-environment.bash

**Comment by Lin-Buo-Ren** [comment]
> OOps, ./setup-development-environment.bash

Yep you've found it ;)

> Does any one packaging this for Debian? (I am DD)

I've [attempt it once](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=869875) but unable to progress at the time.  Am willing to do though, if I have time.
