### ISSUE TITLE
USB becomes non-writable

### ISSUE THREAD

**Issue by darpan5552** [slacka/WoeUSB#338]
I created a bootable disk using woeusb command line.
My command was `sudo woeusb --target-filesystem NTFS --device win10.iso /dev/sdc`
It was not successful, so I decided to format it and retry the process.
Surprisingly, **Unable to format drive because of read-only mode. Tried many solutions from internet, none worked.**
_Please suggest me a way to save my 32GB pendrive._

**Comment by Lin-Buo-Ren** [comment]
It is likely that your pen drive's life is ended (flash memory drives have a write operation limit, it _will_ break eventually even when normally used).

Luckily in your case, the data remains accessible(some will simply malfunction and not able to recover data from the drive).  The best you can do is replace the drive with a new one.  (For the size mentioned it should be dirt cheap nowadays, like around 20$).

Sorry for not being helpful for the original inquiry.
