### ISSUE TITLE
libwxgtk3.0-0v5 is missing

### ISSUE THREAD

**Issue by hueldoeu** [slacka/WoeUSB#344]
windows 10 got crashed on my super-old pc (modified bios settings) it's from year 2004. i want to install windows 10 20H2 when it's out but i only have linux mint 20 right now. woeusb needs libwxgtk3.0-0v5 but linux mint doesn't have it.

**Comment by darpan5552** [comment]
This guide might help you
https://zoomadmin.com/HowToInstall/UbuntuPackage/libwxgtk3.0-gtk3-0v5

**Comment by hueldoeu** [comment]
didn't help 

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 woeusb : Hängt ab von: libwxgtk3.0-0v5 (>= 3.0.4+dfsg) ist aber nicht installierbar
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.

i don't want to translate it

**Comment by olo3000** [comment]
Looking through packages.ubuntu.com seems libwxgtk3.0-0v5 was discontinued after bionic
and the new version is libwxgtk3.0-gtk3-0v5

https://packages.ubuntu.com/bionic/libwxgtk3.0-0v5
https://packages.ubuntu.com/focal/libwxgtk3.0-gtk3-0v5

**Comment by lyonwolf** [comment]
Hello, following these steps has worked correctly for me:
1- Pasting this command will download the missing dependency.
wget http://mirrors.kernel.org/ubuntu/pool/universe/w/wxwidgets3.0/libwxgtk3.0-0v5_3.0.4+dfsg-3_amd64.deb

2- This will install the downloaded package
sudo dpkg -i libwxgtk*_amd64.deb

3- 
sudo apt -f install

4-
sudo apt update

5-
sudo apt install woeusb
