### ISSUE TITLE
WoeUSB fails to mount

### ISSUE THREAD

**Issue by xykrr** [slacka/WoeUSB#345]
Any clue what this means?
`Installation failed!
Exit code: 256
Log:
WoeUSB v3.3.1
Mounting source filesystem...
mount: /media/woeusb_source_1602316965_14772: mount failed: Operation not permitted.
mount_source_filesystem: Error: Unable to mount source media
Error: Unable to mount source filesystem
Unmounting and removing "/media/woeusb_source_1602316965_14772"...
umount: /media/woeusb_source_1602316965_14772: not mounted.
cleanup_mountpoint: Warning: Unable to unmount "/media/woeusb_source_1602316965_14772".
Some mountpoints are not unmount/cleaned successfully and must be done manually
You may now safely detach the target device
`

**Comment by JonnyTech** [comment]
Did you run the command as `root` or with `sudo`? Root priviliges are required.

**Comment by xykrr** [comment]
Yes

**Comment by xykrr** [comment]
I get the same error when using the terminal variant as well

**Comment by LeonardoHQ** [comment]
Same problem here. Running the program with elevated privileges (root) does not solve the problem.

**Comment by LeonardoHQ** [comment]
> Same problem here. Running the program with elevated privileges (root) does not solve the problem.

I solved the issue by downgrading the package from 5.0.4-1 to version 3.3.1-2 (Manjaro Linux). 
If you, @xykrr, did not clean the pacman cache, just run
 `sudo pacman -U /var/cache/pacman/pkg/woeusb-3.3.1-2-x86_64.pkg.tar.zst `

**Comment by saber716rus** [comment]
Hello. On Rosalinux r12 there is the most problem
Operating System: ROSA Fresh Desktop 2021.1
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.10.70-generic-2rosa2021.1-x86_64 (64-bit)
Graphics Platform: X11
Processors: 6 × AMD FX(tm)-6300 Six-Core Processor
Memory: 7.7 ГиБ of RAM
Graphics Processor: NVC1
![Screenshot_20211005_231423](https://user-images.githubusercontent.com/22714555/136096181-63daaf87-4cc4-4d0c-87b5-87f336f15439.jpg)
.
