### ISSUE TITLE
echo: write error: Invalid argument

### ISSUE THREAD

**Issue by seisdr** [slacka/WoeUSB#347]
root@spiral-pc:/home/spiral# ./woeusb -d p.iso  /dev/sdb
WoeUSB v@@WOEUSB_VERSION@@
==============================
Mounting source filesystem...
Wiping all existing partition table and filesystem signatures in /dev/sdb...
/dev/sdb: 5 bytes were erased at offset 0x00008001 (udf): 43 44 30 30 31
/dev/sdb: 8 bytes were erased at offset 0x00000200 (gpt): 45 46 49 20 50 41 52 54
/dev/sdb: 8 bytes were erased at offset 0x737cffe00 (gpt): 45 46 49 20 50 41 52 54
/dev/sdb: 2 bytes were erased at offset 0x000001fe (PMBR): 55 aa
/dev/sdb: calling ioctl to re-read partition table: Success
Ensure that /dev/sdb is really wiped...
Creating new partition table on /dev/sdb...
Creating target partition...
Making system realize that partition table has changed...
Wait 3 seconds for block device nodes to populate...
mkfs.fat 4.1 (2017-01-24)
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
Mounting target filesystem...
Applying workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
Copying files from source media...
Installing GRUB bootloader for legacy PC booting support...
Installing for i386-pc platform.
Installation finished. No error reported.
Installing custom GRUB config for legacy PC booting...
Resetting workaround to prevent 64-bit systems with big primary memory from being unresponsive during copying files.
./woeusb: line 1679: echo: write error: Invalid argument
The command "exit 0" failed with exit status "1", program is prematurely aborted
root@spiral-pc:/home/spiral#

**Comment by fbuetler** [comment]
#324 reports the same issue. And I ran into the same problem today.

**Comment by seisdr** [comment]
any way to use rufus with winehq?
