### ISSUE TITLE
An error Covering most of the screen when using NTFS to install

### ISSUE THREAD

**Issue by MebishP** [slacka/WoeUSB#359]
Installation failed!
Exit code: 256
Log:
WoeUSB v3.3.1
==============================
Mounting source filesystem...
Wiping all existing partition table and filesystem signatures in /dev/sdb...
/dev/sdb: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
/dev/sdb: calling ioctl to re-read partition table: Success
Ensure that /dev/sdb is really wiped...
Creating new partition table on /dev/sdb...
Creating target partition...
Making system realize that partition table has changed...
Wait 3 seconds for block device nodes to populate...
Cluster size has been automatically set to 4096 bytes.
Creating NTFS volume structures.
mkntfs completed successfully. Have a nice day.
--2022-06-06 09:23:18--  https://github.com/pbatard/rufus/raw/master/res/uefi/uefi-ntfs.img
Resolving github.com (github.com)... 13.234.210.38
Connecting to github.com (github.com)|13.234.210.38|:443... pulse
connected.
HTTP request sent, awaiting response... pulse
302 Found
Location: https://raw.githubusercontent.com/pbatard/rufus/master/res/uefi/uefi-ntfs.img [following]
--2022-06-06 09:23:18--  https://raw.githubusercontent.com/pbatard/rufus/master/res/uefi/uefi-ntfs.img
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... pulse
connected.
HTTP request sent, awaiting response... pulse
200 OK
Length: 1048576 (1.0M) [application/octet-stream]
Saving to: ‘/tmp/WoeUSB.MWSJtT.tempdir/uefi-ntfs.img’
     0K .......... .......... .......... .........pulse
. ..........  4% 1.14M 1s
    50K .......... .......... .......... .......... .....pulse
.....  9% 1.56M 1s
   100K .......... .......... .......... .......... .......... 14% 5.28M 0s
   150K .......... .......... .......... .......... .......... 19% 6.93M 0s
   200K .......... .......... .......... .......... .......... 24% 2.32M 0s
   250K .......... .......... .......... .......... .......... 29% 7.43M 0s
   300K .......... .......... .......... .......... .......... 34% 6.86M 0s
   350K .pulse
......... .......... .......... .......... .......... 39% 4.04M 0s
   400K .......... .......... .......... .......... .......... 43% 7.42M 0s
   450K .......... .......... .......... .......... .......... 48% 7.83M 0s
   500K .......... .......... .......... .......... .......... 53% 6.76M 0s
   550K .......... .......... .......... .......... .......... 58% 4.05M 0s
   600K .......... .......... .......... .......... .......... 63% 7.17M 0s
   650K .....pulse
..... .......... .......... .......... .......... 68% 7.15M 0s
   700K .......... .......... .......... .......... .......... 73% 6.57M 0s
   750K .......... .......... .......... .......... .......... 78% 5.23M 0s
   800K .......... .......... .......... .......... .......... 83% 5.33M 0s
   850K .......... .......... .......... .......... .......... 87% 6.53M 0s
   900K .......... .......... .......... .......... .......... 92% 7.15M 0s
   950K .......... .......... .......... .......... .......... 97%pulse
 6.90M 0s
  1000K .......... .......... ....                            100% 10.4M=0.2s
2022-06-06 09:23:19 (4.30 MB/s) - ‘/tmp/WoeUSB.MWSJtT.tempdir/uefi-ntfs.img’ saved [1048576/1048576]
dd: writing to '/dev/sdb2': No space left on device
1025+0 records in
1024+0 records out
524288 bytes (524 kB, 512 KiB) copied, 0.278529 s, 1.9 MB/s
The command "dd if="${download_directory}/uefi-ntfs.img" of="${uefi_ntfs_partition}"" failed with exit status "1", program is prematurely aborted
Unmounting and removing "/media/woeusb_source_1654487588_37453"...
You may now safely detach the target device

**Comment by brlin-tw** [comment]
This is a known issue(WoeUSB/WoeUSB#81), please use the new version from the new project.
