### ISSUE TITLE
grub-install: warning: Attempting to install GRUB to a disk with multiple partition labels.  This is not supported yet.. during installing GRUB

### ISSUE THREAD

**Issue by Elronnd** [slacka/WoeUSB#61]
I downloaded WUSB, installed, ran, and eventually got the following error:

```
# winusb --format /home/elronnd/Win10_1607_English_x64.iso /dev/sdc
Formatting device...
Wait 3 seconds for block device nodes to populate...
mkfs.fat 4.0 (2016-05-06)
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
Mounting...
mount: /dev/loop0 is write-protected, mounting read-only
Copying...
Installing grub...
Installing for i386-pc platform.
grub-install: warning: Attempting to install GRUB to a disk with multiple partition labels.  This is not supported yet..
grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
grub-install: error: will not proceed with blocklists.
Error occured!
Syncing...
Cleaning...
Unmounting and removing '/media/winusb_iso_1470460040_14269'...
Unmounting and removing '/media/winusb_target_1470460040_14269'...
```

What can I do about this?  Right now I'm seeing what happens if I manually format `/dev/sdc` with just one partition, and running with `--install` instead of `--format`, and will report back, but even if it works, there seems to be an underlying problem.

If I manually use mkfs.fat to make a no FS on `/dev/sdb` and then run WUSB, I get the following error:

```
# winusb --install Win10_1607_English_x64.iso /dev/sdb
Mounting...
mount: /dev/loop0 is write-protected, mounting read-only
Copying...
Installing grub...
Installing for i386-pc platform.
grub-install: warning: File system `fat' doesn't support embedding.
grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
grub-install: error: will not proceed with blocklists.
Error occured!
Syncing...
Cleaning...
Unmounting and removing '/media/winusb_iso_1470462225_3168'...
Unmounting and removing '/media/winusb_target_1470462225_3168'...
```

**Comment by dragontortoise** [comment]
I had the same issue.  I followed Mr. enigmaticPhysicist's method and it works.

"""
Nuke the gap between the boot sector and the first partition.

# dd if=/dev/zero of=/dev/sdX seek=1 count=2047

That's for if the first partition starts at sector 2048. Some start earlier, especially on drives that were partitioned by Windows. To be sure, run

# fdisk -l /dev/sdX

before starting and check to see where the first partition starts. Use count=S-1, where S is the start of the first partition.
"""

http://askubuntu.com/questions/666527/install-grub-claims-that-i-have-multiple-partiton-labels-and-that-embedding-is

**Comment by Lin-Buo-Ren** [comment]
It seems that the post-MBR gap may contain data that confuses `grub-install` to believe that multiple partition table/label exists on disk.  Thus it's not a WinUSB bug but GNU GRUB's bug.

The proper way to deal with this problem might be using the `wipefs` command from util-linux to erase all partition table signatures on disk.

I'm not sure if it's sane to do something in WinUSB to prevent this issue(like running `wipefs` to erase all non-MBR signatures before running `grub-install`), I'll keep this issue for a while to see if anyone encounter the same issue and resolve it using the `wipefs` command.

@Elronnd Do you still can reproduce this issue?

**Comment by Lin-Buo-Ren** [comment]
> If I manually use mkfs.fat to make a no FS on /dev/sdb and then run WUSB, I get the following error:

GRUB in IBM PC-compatible boot mode requires a post-MBR gap for installing it's 2nd phase bootstrapping code, which isn't even existed if you use mkfs.fat on an entire disk(/dev/sdb) (partition-less setup is not supported by WinUSB)
