### ISSUE TITLE
mv: cannot move 'PATH' to a subdirectory of itself 'PATH'

### ISSUE THREAD

**Issue by skullscream** [slacka/WoeUSB#96]
I get this error when trying to make bootable Windows 8.1. I downloaded the iso straight from microsoft's website.

```
[phoenix@phoenixPC Downloads]$ sudo winusb --install Win8.1_EnglishInternational_x64.iso /dev/sdc1
Mounting...
mount: /dev/loop0 is write-protected, mounting read-only
Copying...
mv: cannot move '/media/winusb_target_1494667963_9648/BOOT' to a subdirectory of itself, '/media/winusb_target_1494667963_9648/boot/BOOT'
Error occured !
Syncing...
Cleaning...
Umounting and removing '/media/winusb_iso_1494667963_9648'...
Umounting and removing '/media/winusb_target_1494667963_9648'...
```
This is CLI. On GUI i cannot even start, as soon as I press install it says:
```
Installation failed !
Exit code: 256
Log:
```

**Comment by Lin-Buo-Ren** [comment]
> On GUI i cannot even start, as soon as I press install it says:

```
Installation failed !
Exit code: 256
Log:
```

I suspect this is because your system doesn't have `gksudo` command(which is used by GUI to call CLI with root permission), can you tell if it's correct?

**Comment by IronJaeger** [comment]
I had the same problem, I don't have gksudo. For the CLI side , try to log to root (sudo su) instead of using sudo, it works that way

**Comment by Lin-Buo-Ren** [comment]
Hello, the GUI issue should be resolved as recent version of WoeUSB used `pkexec` instead of `gksudo` to call the CLI

As for the issue in CLI it shouldn't be reproduced now as `src/woeusb` no longer calls `mv` command.

Please comment if you still encounter issue using the latest release, thanks!
